# ruff: noqa: E501
"""Discrete Round 1 concerns and the evidence for each six-case revision."""

from __future__ import annotations

REVIEW_ITEMS: tuple[dict[str, str], ...] = (
    {
        "id": "VAL-801-C01",
        "case": "VAL-801",
        "comment": "C1 overall Fail. Presentation, fit, and hospital course are 2. Comment: “The patient presents with delirium, but the cause is not revealed during the hospital course, we just learn that the delirium improves with treatment. There are no further details on why the patient was delirious or why he improved. It is also not clear why the ibuprofen was stopped. I would add that he is discovered to have an infection or GI bleed or something that would explain this better.”",
        "revision": "Added poor oral intake, dry mucous membranes, and a 20 mmHg orthostatic fall as the volume-depletion precipitant. Did not add infection or gastrointestinal bleeding. Removed the unsupported ibuprofen stop.",
        "location": "presentation; admission_note; hospital_course; home_medications; inpatient_medications; reference_discharge_plan",
        "old": "The note names delirium and says it improves with treatment. It does not name a precipitant. Ibuprofen is held, and the reference action is stop.",
        "new": "The note records poor oral intake, dry mucous membranes, and a 20 mmHg orthostatic fall from the supine pressure of 136 mmHg. Confusion clears as intake improves. Ibuprofen stays available for symptomatic analgesia. Glucose remains 163 mg/dL then 103 mg/dL. Creatinine remains 1.1 mg/dL then 1.0 mg/dL.",
        "reasoning": "The original representation labels delirium due to a physiological condition but does not show a physiological cause or a treatment-response relationship, so the medication implications of the stay are not interpretable. The comment offers infection or gastrointestinal bleeding as examples. Those diagnoses were not added. Either one would open a separate illness and a separate medication pathway that the chart does not contain. Volume depletion was selected because poor intake is a recognized reversible precipitant and because the chart already shows stable creatinine and a fall in glucose from 163 mg/dL to 103 mg/dL. The dry membranes, the poor-intake history, and the orthostatic fall are synthetic history and examination findings. They were not in the original chart. The literature supports their plausibility. It does not prove that this patient had them. The supine pressure of 136/78 mmHg is the recorded vital sign. The resident chart and the hidden reference both change: the chart shows the precipitant, and the reference continues ibuprofen.",
        "evidence": "[E1] [E2] [E3] [E4]",
        "status": "REVISED",
    },
    {
        "id": "VAL-801-C02",
        "case": "VAL-801",
        "comment": "C2 Fail. Comment: “It wasn’t clear why ibuprofen should be stopped.”",
        "revision": "Reference action changed from stop to continue.",
        "location": "reference_discharge_plan",
        "old": "Reference action stop.",
        "new": "Reference action continue, for symptomatic analgesia.",
        "reasoning": "The chart records no bleeding, no kidney injury, and creatinine of 1.1 mg/dL then 1.0 mg/dL. Stopping ibuprofen is not interpretable from those facts. Continuing it removes the unsupported action. This change is in the hidden reference and in the resident medication status, which no longer says the drug was held.",
        "evidence": "[E1] [E4]",
        "status": "REVISED",
    },
    {
        "id": "VAL-801-C03",
        "case": "VAL-801",
        "comment": "C3 has both Pass and Fail selected. The comment is blank.",
        "revision": "No change made. Both selections are preserved.",
        "location": "round 1 historical record",
        "old": "Pass and Fail both selected. Comment blank.",
        "new": "Pass and Fail both selected. Comment blank.",
        "reasoning": "The source form contains two selected answers and no comment. Choosing one answer, or inferring a medication change from the blank, would invent the review.",
        "evidence": "[E1]",
        "status": "SOURCE_SELECTION_AMBIGUITY",
    },
    {
        "id": "VAL-801-C04",
        "case": "VAL-801",
        "comment": "C4 Fail. Issue: “Ibuprofen stopped on admission.” Location: “In home medication list.” Meaning: “No obvious indication for why this should be stopped.” Comment: “Not clear why ibuprofen was stopped.”",
        "revision": "The home and inpatient ibuprofen rows are no longer held.",
        "location": "home_medications; inpatient_medications",
        "old": "Ibuprofen status held. The history said it was stopped during the admission.",
        "new": "Ibuprofen 400 mg orally every 8 hours as needed remains on the home and inpatient lists without a hold.",
        "reasoning": "This is the same unsupported stop named in C1 and C2. The medication list is clearer when the drug remains available and no invented indication is attached to it.",
        "evidence": "[E1] [E4]",
        "status": "REVISED",
    },
    {
        "id": "VAL-801-C05",
        "case": "VAL-801",
        "comment": "C5 Inappropriate / outlier. Comment: “Case is unclear.” Overall Revise. Comment: “This case could be usable if there was more complexity to the clinical case, i.e infection discovered and treated. Delirium due to known physiologic condition and then not elaborating on the physiologic condition doesn’t make sense. Medication list should be clearer.”",
        "revision": "The physiological condition is now volume depletion. Infection was not added.",
        "location": "presentation; hospital_course",
        "old": "Diagnosis label without a named physiological condition.",
        "new": "Poor intake, dry mucous membranes, orthostasis, and improvement with restored intake.",
        "reasoning": "The overall comment asks for the missing physiological condition and gives infection as an example. Volume depletion supplies that condition without adding a second diagnosis. The difficulty rating was not relabeled.",
        "evidence": "[E1] [E2]",
        "status": "REVISED",
    },
    {
        "id": "VAL-802-C01",
        "case": "VAL-802",
        "comment": "C1 overall Fail. Fit and hospital course are 1. Comment: “delirium cause is not revealed (delirium due to known physiologic condition doesn’t make sense), it doesn’t appear that anything happened in the hospital course, creatinine was the only lab value and changed slightly, but it was not clear what the baseline creatinine was.”",
        "revision": "Added poor oral intake as the precipitant and stated the recorded creatinine pair. No baseline creatinine was added.",
        "location": "presentation; admission_note; hospital_course; laboratories",
        "old": "The course discusses medication history and does not name a precipitant. Creatinine is 1.3 mg/dL then 1.2 mg/dL. No earlier value is stored.",
        "new": "Poor oral intake for two days is the only recorded precipitant. Confusion improves as intake resumes. The same two creatinine values are stated. No third value was added. Blood pressure is 138/69 mmHg then 124/68 mmHg.",
        "reasoning": "The course does not give a physiological explanation, so the medication implications are not interpretable. Poor intake is a recognized delirium precipitant and does not require a new laboratory. That history is synthetic. It was not in the original chart. A baseline creatinine was not invented. No pre-admission value exists in the clean chart, and choosing a number such as 1.2 mg/dL would manufacture the fact needed to force a lisinopril decision. The resident chart changes. The laboratory table does not.",
        "evidence": "[E1] [E2] [E5]",
        "status": "REVISED",
    },
    {
        "id": "VAL-802-C02",
        "case": "VAL-802",
        "comment": "C1 also says the note “said that she was taking the statin, but this was not continued at discharge for no obvious reason.” C2 Fail: “Was the trainee supposed to continue the statin? Or recognize that it was not continued?” C3 Fail: “Case lacks clinical complexity and reasoning for stopping the statin.”",
        "revision": "Removed the sentence that said a continued statin had been confirmed. Atorvastatin remains on the home and inpatient lists and in the reference.",
        "location": "admission_note; hospital_course; CaseMedicationReconciliation.notes; reference_discharge_plan",
        "old": "The reconciliation note said a pharmacy history “confirmed a continued statin,” while other sentences said stopped medicines were recorded separately. The medication rows themselves continue atorvastatin 40 mg daily.",
        "new": "The note says a pharmacy fill history was used to verify the home list and that atorvastatin 40 mg daily is on that list. The reference action remains continue.",
        "reasoning": "The clean medication rows and the clean reference continue atorvastatin. The prose around verification made it sound as if the statin might have been stopped, which is what the comment describes. The revision removes that contradiction. It does not stop the statin, because the source list does not stop it, and it does not tell the resident that continuation is the required answer.",
        "evidence": "[E1] [E5]",
        "status": "REVISED",
    },
    {
        "id": "VAL-802-C03",
        "case": "VAL-802",
        "comment": "C4 Fail. Issue: “Creatinine elevated but patient continued on lisinopril.” Location: “Lab data.” Meaning: “If creatinine was elevated to point of AKI the lisinopril should be stopped.” Comment: “As above.”",
        "revision": "Lisinopril was not stopped. A hold is an acceptable alternative.",
        "location": "reference_discharge_plan; acceptable_alternatives",
        "old": "Reference continues lisinopril. No alternative is recorded.",
        "new": "Reference continues lisinopril. Hold is acceptable if 1.3 mg/dL is judged to be acute kidney injury.",
        "reasoning": "The only creatinine values are 1.3 mg/dL and 1.2 mg/dL. The comment says the change is slight and that a baseline is missing, and also says lisinopril should be stopped if the value represents acute kidney injury. Those statements do not establish that threshold. KDIGO reviews ACE-inhibitor exposure when kidney function worsens, but it does not supply a baseline that was not measured. Continuing the recorded order is the reference. Holding it is acceptable. Neither is encoded as the only plan. This change is in the hidden reference.",
        "evidence": "[E1] [E5] [E6]",
        "status": "REQUIRES_CLINICIAN_DECISION",
    },
    {
        "id": "VAL-802-C04",
        "case": "VAL-802",
        "comment": "C5 Inappropriate / outlier. Comment: “This case is unclear and intended discharge medications are not stated.” Overall Exclude. Comment: “Would exclude, this case would need major revisions to be compatible with the goals of this project.”",
        "revision": "The precipitant and the statin wording were revised. The case was not dropped from the revised set.",
        "location": "presentation; hospital_course",
        "old": "Unexplained delirium and conflicting statin prose.",
        "new": "Poor oral intake is named, and atorvastatin remains on the verified list without an instruction to continue it.",
        "reasoning": "Exclude is the recorded recommendation. The revision makes the course and the statin row interpretable so a second review can judge whether the case is usable. The Exclude selection is preserved in the historical record and was not changed to Revise.",
        "evidence": "[E1]",
        "status": "REVISED",
    },
    {
        "id": "VAL-803-C01",
        "case": "VAL-803",
        "comment": "C1 overall Fail. Fit is 1 and hospital course is 1. Comment: “Cause is not revealed during the hospital course. Medication list is fine but no changes that need to be made at discharge. Her creatinine changes so this might be considered clinically relevant or why the patient receives only 7 days of lisinopril.”",
        "revision": "The course now states the creatinine pair. The hidden reference keeps a 30-day lisinopril supply. No discharge medicine was stopped.",
        "location": "hospital_course; reference_discharge_plan.lisinopril.duration",
        "old": "The course says cognition returned and does not state the creatinine values. The reviewed readable discharge list gave lisinopril a 7-day supply.",
        "new": "The course states that no precipitant is recorded, creatinine is 1.0 mg/dL then 1.2 mg/dL, and potassium is 4.4 mmol/L then 4.2 mmol/L. The reference duration is 30 days. Hydrochlorothiazide, lisinopril, atorvastatin, and metformin remain continued.",
        "reasoning": "The completed comment says the medication list is fine and that no discharge change is needed, then asks why the supply is 7 days and whether the creatinine change explains it. The 7-day supply is the injected discrepancy in the reviewed readable case. The preserved reference uses 30 days, the same duration as the other discharge medicines. Creatinine rises from 1.0 mg/dL to 1.2 mg/dL. That pair is already stored. A rise of 0.2 mg/dL is now visible and is not used to stop lisinopril. The day-supply correction is in the hidden reference. The resident chart shows the laboratory pair and does not announce the reference duration. No precipitant was invented, because the comment does not name one and the review stopped after C1.",
        "evidence": "[E1] [E7]",
        "status": "REVISED",
    },
    {
        "id": "VAL-803-C02",
        "case": "VAL-803",
        "comment": "C2, C3, C4, C5, the overall recommendation, the reviewer code, and the date were not completed.",
        "revision": "No change made from the uncompleted items.",
        "location": "round 1 historical record",
        "old": "NOT COMPLETED IN ROUND 1.",
        "new": "NOT COMPLETED IN ROUND 1.",
        "reasoning": "The review stopped after C1. Later ratings were not inferred.",
        "evidence": "[E1]",
        "status": "NOT_COMPLETED_IN_ROUND_1",
    },
    {
        "id": "VAL-803-C03",
        "case": "VAL-803",
        "comment": "Thiazide-associated hyponatremia was considered after Round 1 because hydrochlorothiazide is on the list. The reviewer did not request that diagnosis.",
        "revision": "No sodium series was added, and hydrochlorothiazide was not stopped.",
        "location": "laboratories; reference_discharge_plan",
        "old": "No sodium values. Hydrochlorothiazide 25 mg daily is continued.",
        "new": "No sodium values. Hydrochlorothiazide 25 mg daily is continued.",
        "reasoning": "The reviewer did not request hyponatremia. The completed comment says the medication list is fine and that no discharge change is needed. Sodium 128 mmol/L then 135 mmol/L does not exist in the clean chart. Adding it would be a synthetic laboratory series used to justify stopping hydrochlorothiazide, which contradicts the completed comment. Hydrochlorothiazide remains because it is a source medicine. Labeling supports that thiazides can cause hyponatremia. That fact was not used to create a sodium value.",
        "evidence": "[E1] [E7] [E8]",
        "status": "NOT_CHANGED",
    },
    {
        "id": "VAL-805-C01",
        "case": "VAL-805",
        "comment": "C1 hospital course is 2. Comment: “The weight should be closer to dry weight at the time of discharge.” C3 Fail. Comment: “The discharge weight not being close to the patient’s dry weight is confusing and suggests that the patient is not in fact ready for discharge.”",
        "revision": "No weight was changed. The course states the recorded gap and no longer says euvolemia was reached.",
        "location": "vital_signs.weight; hospital_course",
        "old": "Admission weight 81 kg, discharge weight 78 kg, dry weight 73 kg. The original course said daily weights were used to judge euvolemia.",
        "new": "The same weights. The course states that discharge weight remains 5 kg above dry weight.",
        "reasoning": "Serial weight is the observation used to judge decongestion. The source already shows that gap. Replacing 78 kg or 73 kg so the patient looks ready for discharge would erase the finding the comment identified. The original euvolemia sentence is clinically inconsistent with a discharge weight that has not returned to dry weight, so that sentence was removed. The resident chart changes. The weight table does not.",
        "evidence": "[E1] [E9] [E12]",
        "status": "REVISED",
    },
    {
        "id": "VAL-805-C02",
        "case": "VAL-805",
        "comment": "Medication-regimen score has both 2 and 3 selected. Comment: “The medications during hospitalization would not be the same as the home regimen - the lasix would be given IV and increased.” Overall comment: “should not be the same as the patient’s home regimen.”",
        "revision": "The course states that the charted inpatient furosemide is still 40 mg oral once daily. No intravenous dose was added.",
        "location": "hospital_course; inpatient_medications.furosemide",
        "old": "Home and inpatient furosemide are both 40 mg oral once daily. The course said only that congestion was treated with inpatient diuresis.",
        "new": "The same oral order. The course says no intravenous dose is recorded.",
        "reasoning": "Acute decompensated heart failure with congestion is ordinarily treated with an intravenous loop diuretic at a dose that can differ from the home oral dose. The project’s curated furosemide regimen is 40 mg oral once daily and explicitly excludes the injection product. No intravenous dose is stored for this case. Selecting 40 mg IV twice daily from a guideline range would invent a patient-specific order. The oral row is retained, and the course says so, so the resident can see that the hospitalization is not represented by a distinct diuretic order. The specific intravenous order remains a clinician decision.",
        "evidence": "[E1] [E9] [E10] [E11]",
        "status": "REQUIRES_CLINICIAN_DECISION",
    },
    {
        "id": "VAL-805-C03",
        "case": "VAL-805",
        "comment": "Comment: “it would be more realistic to have several days of input and output data, as well as data on what medications the patient received during the hospitalization.”",
        "revision": "The single recorded intake/output day is stated. Additional days were not invented. The inpatient medication list is the recorded list.",
        "location": "intake_output; inpatient_medications; hospital_course",
        "old": "Hospital day 3 only: intake 1418 mL, output 2463 mL, net -1045 mL. Inpatient medicines are oral furosemide 40 mg daily, metoprolol succinate 25 mg daily, and atorvastatin 40 mg daily.",
        "new": "The same day and the same medication list, now stated in the course.",
        "reasoning": "Net fluid balance is useful for judging decongestion. The case stores one day. Adding further days would require invented volumes. The inpatient medicines are already stored and are now named in the course. The resident can see both the limited fluid record and the medication record.",
        "evidence": "[E1] [E9] [E12]",
        "status": "REVISED",
    },
    {
        "id": "VAL-805-C04",
        "case": "VAL-805",
        "comment": "Comment: “It would be helpful to have either notes from cardiology or echocardiogram data and require the trainee to add additional medications… or adjust their dose of lasix.” Overall comment: “The trainee should have to make decisions on additional medications… ACE/ARB, SGLT2i, MRA.”",
        "revision": "No ejection fraction and no new drug were added. Additional systolic heart-failure therapy is an acceptable alternative, not a required action. The cardiology sentence that said to continue the intended plan was replaced.",
        "location": "consultations; imaging; acceptable_alternatives; reference_discharge_plan",
        "old": "Diagnosis: acute systolic heart failure. Chest radiograph: pulmonary edema. No ejection fraction. Cardiology recommendation: “Continue the intended heart-failure and diuretic plan.” Reference continues furosemide, metoprolol, and atorvastatin.",
        "new": "The same diagnosis, radiograph, and three medicines. The consultation says no echocardiogram and no specific medication change are recorded. Starting an ACE inhibitor, an ARNI, an SGLT2 inhibitor, or a mineralocorticoid antagonist is an acceptable alternative.",
        "reasoning": "The diagnosis already identifies systolic heart failure. A numeric ejection fraction is not in the chart, so 30 percent was not added. Guideline-directed therapy includes a beta blocker, renin-angiotensin inhibition or an ARNI, a mineralocorticoid antagonist, and an SGLT2 inhibitor when tolerated. Metoprolol succinate is already recorded. Admission creatinine is 1.7 mg/dL and falls to 0.9 mg/dL. Potassium is 4.7 mmol/L then 4.3 mmol/L. Blood pressure is 109/82 mmHg then 110/84 mmHg. The admission creatinine argues against starting renin-angiotensin blockade while the patient is still congested. The discharge values do not prohibit an additional class, and they do not make every class mandatory. The original cardiology sentence told the resident to continue a plan without stating the plan, so it was replaced with what the chart actually lacks. The required reference stays the recorded regimen. The decision to add a class is available to the resident and is not pre-answered.",
        "evidence": "[E1] [E9] [E10]",
        "status": "REVISED",
    },
    {
        "id": "VAL-805-C05",
        "case": "VAL-805",
        "comment": "C2 Pass, with no comment. C4 Pass, with blank issue fields. C5 Moderate, with no comment.",
        "revision": "No change made from these selections.",
        "location": "round 1 historical record",
        "old": "C2 Pass. C4 Pass. C5 Moderate.",
        "new": "C2 Pass. C4 Pass. C5 Moderate.",
        "reasoning": "Pass on C2 and C4 means those items were not marked as an unwanted discrepancy. Moderate is a difficulty rating. None of the three supplies a medication to add or remove.",
        "evidence": "[E1]",
        "status": "NOT_CHANGED",
    },
    {
        "id": "VAL-809-C01",
        "case": "VAL-809",
        "comment": "C1 presentation and hospital course are 2. Comment: “should present with fevers, have a history of mechanical valve or poor dentition that would predispose to endocarditis.” Overall comment: “Would have fevers/chills/predisposition to endocarditis.”",
        "revision": "The recorded fatigue, cultures, vegetation, and temperature were written into the course. Fever, a mechanical valve, and poor dentition were not added.",
        "location": "admission_note; hospital_course; vital_signs.temperature",
        "old": "The course said parenteral therapy was planned. It did not describe the vegetation or the cultures. Temperature is 36.80°C. The stored symptom is fatigue. No valve or dental history is stored.",
        "new": "The course records fatigue, gram-positive cocci in blood, a later culture with no growth, a vegetation with preserved ventricular function, ceftriaxone 2 g IV daily, and temperature 36.80°C on admission and at discharge.",
        "reasoning": "The resident cannot interpret the antibiotic from a course that omits the recorded evidence. That evidence is now visible. The recorded temperature is 36.80°C. Replacing it with a fever would erase a source vital sign. A mechanical valve is not in the chart and would add a major comorbidity. Poor dentition and a dental procedure are not in the archetype or the chart, and the culture is not identified as an oral streptococcus, so either addition would imply a source the microbiology does not establish. The existing bacteremia and vegetation are sufficient to make the endocarditis representation interpretable.",
        "evidence": "[E1] [E13] [E14] [E15]",
        "status": "REVISED",
    },
    {
        "id": "VAL-809-C02",
        "case": "VAL-809",
        "comment": "C1: “AKI was unexplained and lisinopril was continued despite AKI.” C2 Fail: “Lisinopril was continued despite the patient having an AKI.” C4 Fail. Issue: “Lisinopril - AKI.” Location: “Medications.” Meaning: “Should not be continued.” Overall: “Lisinopril should be held if the patient has an AKI.”",
        "revision": "The creatinine pair is stated. Lisinopril was not changed to a required hold.",
        "location": "hospital_course; laboratories; reference_discharge_plan; acceptable_alternatives",
        "old": "Creatinine 1.3 mg/dL then 0.8 mg/dL, not discussed in the course. Reference continues lisinopril.",
        "new": "The course states those values and states that no pre-admission creatinine is recorded. Reference continues lisinopril. Hold is an acceptable alternative.",
        "reasoning": "The comment says the drug should be held if the patient has acute kidney injury, and the C4 line says it should not be continued. The chart shows a fall from 1.3 mg/dL to 0.8 mg/dL and no creatinine from before the admission. Treating 0.8 mg/dL as a baseline would be an inference, not a stored measurement. KDIGO supports reviewing ACE-inhibitor exposure when kidney function worsens. It does not create the missing baseline. A required hold would assert acute kidney injury that the chart does not establish. The recorded order continues lisinopril. Holding it is acceptable because the admission value is higher and the baseline is unknown. The resident chart shows the pair. The required-versus-acceptable distinction is in the hidden reference.",
        "evidence": "[E1] [E6] [E13]",
        "status": "REQUIRES_CLINICIAN_DECISION",
    },
    {
        "id": "VAL-809-C03",
        "case": "VAL-809",
        "comment": "C3 Pass, with no comment. C5 Inappropriate / outlier. Comment: “Error in the case as described above.” Overall: “Patient of this age would be very likely to have more than 2 home medications.”",
        "revision": "No home medicine was added.",
        "location": "home_medications",
        "old": "Home medicines are lisinopril and atorvastatin.",
        "new": "The same two home medicines.",
        "reasoning": "A longer home list would be a new fact. The comment asks for more complexity, not for a named third drug. Adding medicines would make the case broader. C3 Pass was not converted into a new discrepancy. Ceftriaxone 2 g IV daily remains the recorded antibiotic.",
        "evidence": "[E1] [E13] [E15]",
        "status": "NOT_CHANGED",
    },
    {
        "id": "VAL-813-C01",
        "case": "VAL-813",
        "comment": "C1 medication regimen is 1. Comment: “Patient is admitted for new diagnosis of CMV colitis, but was already on treatment for this (valganciclovir) prior to admission, which does not make sense. This medication would be started after diagnosis during the hospitalization.” C2 Fail: being on valganciclovir at admission “would make you think that you need to change to an alternative regimen.” C4 Fail. Issue: “Valganciclovir.” Location: “Admission medications.” Meaning: “Should not be an admission medication.” Comment: “This is an error in the case that would be confusing.”",
        "revision": "Removed valganciclovir from the home list and started 900 mg twice daily after the admission viral-load result.",
        "location": "home_medications; inpatient_medications.valganciclovir; admission_note; hospital_course; reference_discharge_plan",
        "old": "Valganciclovir 900 mg twice daily is a home medicine and an inpatient medicine. The note says the patient is already taking it and that outpatient continuation is the intended plan.",
        "new": "The home list is tacrolimus 1 mg every 12 hours, amlodipine 5 mg daily, and atorvastatin 40 mg daily. Valganciclovir 900 mg twice daily, given as 450 mg tablets, starts after the admission result that detected CMV viral burden. The reference action is start.",
        "reasoning": "The admission diagnosis is CMV disease, and the procedure text says the admission viral-load review detected CMV viral burden and supported antiviral treatment. A pre-admission valganciclovir row contradicts that sequence and creates the false cue that the resident must switch drugs. The home row was removed. The inpatient order remains, timed after the recorded result. Amlodipine and atorvastatin stay because the comment does not question them. The dose remains 900 mg twice daily. The completed comment does not identify a numeric dose error. That dose is the project’s curated treatment regimen when creatinine is in the range these profiles keep, and the charted creatinine is 1.2 mg/dL then 1.0 mg/dL. The 450 mg tablet is the product strength. RxNorm was not used to choose the dose. The resident chart and the hidden reference both change.",
        "evidence": "[E1] [E16] [E17] [E18] [E19]",
        "status": "REVISED",
    },
    {
        "id": "VAL-813-C02",
        "case": "VAL-813",
        "comment": "Comment: “The medications are much too simplified for a post transplant patient.”",
        "revision": "Mycophenolate was not added.",
        "location": "home_medications",
        "old": "The only immunosuppressant on the list is tacrolimus 1 mg every 12 hours.",
        "new": "Tacrolimus remains the only immunosuppressant.",
        "reasoning": "The educational task after the chronology correction is the start of CMV treatment and continuation of the recorded immunosuppressant. Mycophenolate is not on the source list. Adding 1 g twice daily because labeling recommends it for kidney transplantation would invent a home medicine. Continuation, reduction, or a temporary hold of an unrecorded antimetabolite cannot be chosen from this chart. Whether the case is too narrow without it requires a clinician decision. A temporary tacrolimus reduction is an acceptable alternative if the transplant service documents one. No trough and no reduction are recorded, so the reference continues 1 mg every 12 hours.",
        "evidence": "[E1] [E16] [E20]",
        "status": "REQUIRES_CLINICIAN_DECISION",
    },
    {
        "id": "VAL-813-C03",
        "case": "VAL-813",
        "comment": "Comment: “The labs are incomplete and the patient has a change in potassium without obvious cause or indication.” C5 Inappropriate / outlier, with no comment. Overall Exclude, with no comment. Reviewer KO. Date 10/5/2026.",
        "revision": "Potassium 4.7 mmol/L then 3.9 mmol/L is stated. No cause, blood count, or numeric viral load was added.",
        "location": "laboratories; hospital_course",
        "old": "Potassium 4.7 mmol/L then 3.9 mmol/L is stored and not discussed. Viral burden is described as detected, then lower.",
        "new": "The course quotes those potassium values and states that no cause is recorded. The viral-load wording is unchanged.",
        "reasoning": "The recorded pair shows a fall without a stated cause and without a replacement order. Inventing a cause, a complete blood count, or a numeric viral load would add results the case does not contain. Exclude is the recorded recommendation and is preserved. The blank overall comment was not filled in.",
        "evidence": "[E1] [E16]",
        "status": "NOT_CHANGED",
    },
)

EVIDENCE_NOTES: dict[str, str] = {
    "[E1]": "Round 1 form in KO Casebook Validation.docx, reviewer KO, 10/5/2026. Supports the comment text and the blank or conflicting boxes. It does not by itself prove a medication change.",
    "[E2]": "Inouye SK, Westendorp RGJ, Saczynski JS. Delirium in elderly people. Lancet. 2014;383:911-922. doi:10.1016/S0140-6736(13)60688-1. Supports treating the precipitant of delirium. It does not establish which precipitant this synthetic patient had.",
    "[E3]": "Freeman R, Wieling W, Axelrod FB, et al. Consensus statement on the definition of orthostatic hypotension, neurally mediated syncope and the postural tachycardia syndrome. Clin Auton Res. 2011;21:69-72. doi:10.1007/s10286-011-0119-5. Supports the 20 mmHg systolic threshold used for the synthetic orthostatic finding. It does not show that this patient had that finding.",
    "[E4]": "Clean pre-injection VAL-801. Glucose 163 mg/dL then 103 mg/dL, creatinine 1.1 mg/dL then 1.0 mg/dL, supine blood pressure 136/78 mmHg, and ibuprofen on the verified list. No bleeding or kidney-injury indication for stopping ibuprofen is stored.",
    "[E5]": "Clean pre-injection VAL-802. Creatinine 1.3 mg/dL then 1.2 mg/dL. No creatinine from before the admission is stored. Atorvastatin is on the verified list.",
    "[E6]": "KDIGO Clinical Practice Guideline for Acute Kidney Injury. Kidney Int Suppl. 2012;2:1-138. Supports reassessing ACE-inhibitor exposure when kidney function worsens. It does not create a baseline creatinine that was not measured.",
    "[E7]": "Clean pre-injection VAL-803 evaluator. Lisinopril duration 30 days. Creatinine 1.0 mg/dL on admission and 1.2 mg/dL at discharge. Hydrochlorothiazide 25 mg daily is on the list. No sodium is stored. The reviewed readable case, data/case_sets/seed_guided/readable/cases/VAL-803.md, gave lisinopril a 7-day supply.",
    "[E8]": "Hydrochlorothiazide tablet labeling, DailyMed setid 9f0beacd-4c41-432d-b7d6-e779ae4c1b99. Thiazides can cause hyponatremia. That fact was not used to add a sodium value or to stop the drug.",
    "[E9]": "Clean pre-injection VAL-805. Furosemide 40 mg oral once daily at home and in the hospital. Weights 81 kg on admission, 78 kg at discharge, dry weight 73 kg. Hospital day 3 intake 1418 mL, output 2463 mL, net -1045 mL. Blood pressure 109/82 mmHg then 110/84 mmHg. Creatinine 1.7 mg/dL then 0.9 mg/dL. Potassium 4.7 mmol/L then 4.3 mmol/L. B-type natriuretic peptide 1120 pg/mL then 369 pg/mL. Oxygen saturation 92 percent then 98 percent. Chest radiograph shows pulmonary edema. No ejection fraction is stored.",
    "[E10]": "Heidenreich PA, Bozkurt B, Aguilar D, et al. 2022 AHA/ACC/HFSA Guideline for the Management of Heart Failure. Circulation. 2022;145:e895-e1032. doi:10.1161/CIR.0000000000001063. Supports intravenous loop diuretic treatment of congestion and the components of therapy for systolic heart failure. It was not used to invent an intravenous dose, a weight, or an ejection fraction.",
    "[E11]": "Repository regimen FUROSEMIDE_40_DAILY in data/bootstrap/medication_regimens.json. Dose 40 mg, route oral, frequency once daily. The entry excludes the injection product. DailyMed setid 571a52ed-5258-46d5-a0d2-9a984cf73895. Supports the charted oral dose. It does not supply an intravenous order.",
    "[E12]": "Mullens W, Damman K, Harjola VP, et al. The use of diuretics in heart failure with congestion — a position statement from the Heart Failure Association of the ESC. Eur J Heart Fail. 2019;21:137-155. doi:10.1002/ejhf.1369. Supports using weight and urine output to judge decongestion. It was not used to replace the recorded weights.",
    "[E13]": "Clean pre-injection VAL-809. Temperature 36.80°C on admission and at discharge. The stored presenting symptom is fatigue. Blood culture with gram-positive cocci, later culture with no growth. Echocardiogram vegetation with preserved ventricular function. Creatinine 1.3 mg/dL then 0.8 mg/dL. No valve or dental history.",
    "[E14]": "Baddour LM, Wilson WR, Bayer AS, et al. Infective Endocarditis in Adults: Diagnosis, Antimicrobial Therapy, and Management of Complications. AHA Scientific Statement. Circulation. 2015;132:1435-1486. doi:10.1161/CIR.0000000000000296. Supports using bacteremia, echocardiography, and antimicrobial therapy in the case representation. It was not used to add a valve, a dental procedure, or a fever that replaces 36.80°C.",
    "[E15]": "Repository regimen CEFTRIAXONE_ENDOCARDITIS_OPAT. Ceftriaxone 2000 mg intravenous once daily. Supports the dose already charted.",
    "[E16]": "Clean pre-injection VAL-813. Admission diagnosis of CMV disease. Procedure text: admission viral burden detected and supported antiviral treatment; later burden lower. Creatinine 1.2 mg/dL then 1.0 mg/dL. Potassium 4.7 mmol/L then 3.9 mmol/L. Home medicines include tacrolimus 1 mg every 12 hours, amlodipine, atorvastatin, and valganciclovir.",
    "[E17]": "Repository regimen VALGANCICLOVIR_CMV_TREATMENT. Dose 900 mg oral twice daily, given as 450 mg tablets, when renal function is in the range these profiles keep. DailyMed setid 89a934f0-85a3-44c1-82e5-d09d1738e08d. Supports the dose. The dose was not taken from RxNorm.",
    "[E18]": "Kotton CN, Kumar D, Caliendo AM, et al. The Third International Consensus Guidelines on the Management of Cytomegalovirus in Solid-organ Transplantation. Transplantation. 2018;102:900-931. doi:10.1097/TP.0000000000002191. Supports starting treatment after laboratory evidence of CMV and adjusting the dose for renal function. It was not used to invent a viral-load number.",
    "[E19]": "RxNorm identifies valganciclovir. It was not used as evidence for the dose or the start time.",
    "[E20]": "CELLCEPT labeling, DailyMed setid 37241e87-4af4-4dc3-a1aa-ea6f20d8dc40, recommends 1 g orally twice daily for adult kidney transplantation. The source case has no mycophenolate row, so the labeled dose was not added.",
}


LEDGER: tuple[dict[str, str], ...] = (
    {
        "case": "VAL-801",
        "change": "Poor oral intake, dry mucous membranes, and a 20 mmHg orthostatic fall were added to the history and examination.",
        "old": "Not recorded.",
        "new": "Recorded in the admission note and hospital course.",
        "source": "SYNTHETIC_ADDITION_SUPPORTED_BY_LITERATURE. [E2] [E3]. Supine blood pressure 136/78 mmHg is CASE_SOURCE [E4]. The orthostatic fall was not measured in the source chart.",
        "classification": "SYNTHETIC_ADDITION_SUPPORTED_BY_LITERATURE",
    },
    {
        "case": "VAL-801",
        "change": "Ibuprofen stop removed.",
        "old": "Reference action stop.",
        "new": "Reference action continue, symptomatic analgesia.",
        "source": "CASE_SOURCE [E4]. No bleeding or kidney-injury indication is stored.",
        "classification": "CASE_SOURCE",
    },
    {
        "case": "VAL-802",
        "change": "Poor oral intake added as the delirium precipitant.",
        "old": "No precipitant recorded.",
        "new": "Poor oral intake for two days. No other precipitant recorded.",
        "source": "SYNTHETIC_ADDITION_SUPPORTED_BY_LITERATURE [E2]. No new laboratory value was added.",
        "classification": "SYNTHETIC_ADDITION_SUPPORTED_BY_LITERATURE",
    },
    {
        "case": "VAL-802",
        "change": "No baseline creatinine added.",
        "old": "1.3 mg/dL then 1.2 mg/dL.",
        "new": "1.3 mg/dL then 1.2 mg/dL.",
        "source": "CASE_SOURCE [E5].",
        "classification": "NOT_CHANGED",
    },
    {
        "case": "VAL-802",
        "change": "Answer-key statin sentence removed.",
        "old": "The note said the statin should be continued.",
        "new": "The medicine remains on the list without that instruction.",
        "source": "CASE_SOURCE medication row [E5]. The sentence was an answer leak.",
        "classification": "CASE_SOURCE",
    },
    {
        "case": "VAL-803",
        "change": "Lisinopril duration restored to 30 days.",
        "old": "Injected reference duration 7 days.",
        "new": "30 days.",
        "source": "CASE_SOURCE [E7].",
        "classification": "CASE_SOURCE",
    },
    {
        "case": "VAL-803",
        "change": "No sodium series added.",
        "old": "No sodium stored.",
        "new": "No sodium stored.",
        "source": "CASE_SOURCE [E7]. Labeling [E8] was not used to invent a value.",
        "classification": "NOT_CHANGED",
    },
    {
        "case": "VAL-805",
        "change": "Intravenous furosemide not charted.",
        "old": "40 mg oral once daily.",
        "new": "40 mg oral once daily.",
        "source": "CASE_SOURCE [E9] and DATABASE [E11]. LITERATURE [E10] supports IV treatment in principle and was not used to invent a dose.",
        "classification": "REQUIRES_CLINICIAN_DECISION",
    },
    {
        "case": "VAL-805",
        "change": "Weights and the single intake/output day retained. The euvolemia sentence was removed.",
        "old": "81 kg, dry weight 73 kg, discharge 78 kg; hospital day 3 intake 1418 mL, output 2463 mL, net -1045 mL. Course claimed euvolemia.",
        "new": "Same measurements. Course states that discharge weight remains above dry weight.",
        "source": "CASE_SOURCE [E9]. LITERATURE [E12] supports using those observations and was not used to replace them.",
        "classification": "CASE_SOURCE",
    },
    {
        "case": "VAL-805",
        "change": "No ejection fraction added.",
        "old": "Systolic heart-failure diagnosis, no numeric EF.",
        "new": "Same.",
        "source": "CASE_SOURCE [E9].",
        "classification": "NOT_CHANGED",
    },
    {
        "case": "VAL-809",
        "change": "Recorded endocarditis evidence moved into the course. Temperature, valve history, and microbiology were not replaced.",
        "old": "Temperature 36.80°C. Gram-positive cocci. Vegetation.",
        "new": "Same facts, now stated in the course.",
        "source": "CASE_SOURCE [E13]. LITERATURE [E14] supports the disease representation.",
        "classification": "CASE_SOURCE",
    },
    {
        "case": "VAL-809",
        "change": "Lisinopril hold is an acceptable alternative, not a required stop.",
        "old": "Continued.",
        "new": "Continued, with hold acceptable.",
        "source": "CASE_SOURCE creatinine pair [E13]. LITERATURE [E6]. No baseline creatinine was invented.",
        "classification": "REQUIRES_CLINICIAN_DECISION",
    },
    {
        "case": "VAL-813",
        "change": "Valganciclovir removed from the home list and started after the admission viral-load result.",
        "old": "Home and inpatient, 900 mg twice daily.",
        "new": "Inpatient start after the recorded detection. Dose unchanged.",
        "source": "CASE_SOURCE procedure text and diagnosis [E16]. The home row was removed because it contradicted that sequence.",
        "classification": "CASE_SOURCE",
    },
    {
        "case": "VAL-813",
        "change": "Dose left at 900 mg twice daily.",
        "old": "900 mg twice daily, 450 mg tablets.",
        "new": "900 mg twice daily, 450 mg tablets.",
        "source": "DATABASE [E17]. Creatinine 1.2 then 1.0 mg/dL is CASE_SOURCE [E16]. RxNorm was not used to set the dose [E19].",
        "classification": "DATABASE",
    },
    {
        "case": "VAL-813",
        "change": "Mycophenolate not added.",
        "old": "Not on the list.",
        "new": "Not on the list.",
        "source": "CASE_SOURCE [E16]. Labeling [E20] was not used to add the drug.",
        "classification": "REQUIRES_CLINICIAN_DECISION",
    },
)
