"""Static Markdown for derived CliniProof clinician/technical packets.

These strings are copied into data/validation/readable/ by the generator.
They discuss mechanisms generically and must not map a VAL ID to a hidden target.
"""

from __future__ import annotations

ABOUT_CASE_DATA = """## About the case data

This is a synthetic case created for medication-reconciliation assessment. It is not an extract from an individual patient’s medical record.

Medication names, diagnoses, and laboratory tests are drawn from established clinical terminology sources so that the concepts can be cited. Patient-specific values such as age, vital signs, and numeric laboratory results, and the surrounding clinical scenario, are generated by the software.

The case has undergone automated checks for structure, terminology consistency, and the implemented clinical constraints. Those checks can detect technical inconsistencies, but they do not establish that the case is clinically realistic, educationally appropriate, or ready for use without clinician review.
"""

ALL_CASES_HEADER = """# CliniProof Clinical Case Set

## CLINIPROOF_TAXONOMY_V1

This freeze is **archived historical provenance**. It is not an active prospective study set. New reviewers should start at [`../../active_validation_sets.md`](../../active_validation_sets.md).

This document is intended for residents, clinicians, medical educators, pharmacists, and clinical informatics collaborators who want to review the clinical cases without reading the underlying JSON representation.

The set contains twenty-four cases, labeled VAL-201 through VAL-224. Each case is a synthetic inpatient encounter assembled for medication-reconciliation review. The software has already checked structure, terminology provenance, and a limited set of implemented clinical rules. Those automated checks do not establish clinical validity. Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

This file contains only the information a resident would see. It does not identify which cases contain an intended assessment problem, if any, and it does not include investigator answer keys.

## How these cases are created

These cases are synthetic rather than extracted from individual patient records.

Clinical concepts such as medication names, diagnoses, and laboratory tests are linked to established terminology sources. Patient-specific values such as age, vital signs, and laboratory results are generated by the software.

The system first creates a structured case and checks its terminology, internal structure, and a limited set of predefined clinical rules. For assessment cases, a specific medication-reconciliation problem may then be introduced in a controlled way. Some cases are left unchanged as clean controls so that a reviewer cannot assume that every chart necessarily contains an error. This file does not say which cases are controls. Human clinician review is required because automated checks cannot establish that a case is clinically realistic or educationally appropriate.

The construction sequence is as follows.

1. A clinical scenario is selected, for example an inpatient heart-failure or pneumonia theme.
2. Medication, diagnosis, and laboratory concepts are resolved against established terminology sources that have already been stored locally.
3. A synthetic patient encounter is constructed, including demographics, vital signs, laboratory values, medication lists, notes, and follow-up.
4. Automated clinical and structural checks are applied to that clean case.
5. For assessment cases, a predefined medication-reconciliation problem may be introduced. Clean controls skip this step.
6. The case is checked again after any assessment modification.
7. Resident-facing and investigator-facing versions are separated. Residents receive the chart. Investigators receive the concealed assessment target separately.
8. Clinicians review the resulting cases before educational use.

Medication reconciliation, in ordinary clinical terms, is the process of comparing what the patient was taking before admission, what was given in the hospital, and what is prescribed at discharge, then ensuring that intended continuations, holds, stops, supplies, monitoring, and follow-up actions are explicit.

Review each case as you would a discharge chart. Ask whether the patient story is coherent, and whether you can complete a careful medication-reconciliation review from the documents provided.
"""

CLINICIAN_PACKET_HEADER = """# CliniProof clinician validation packet

## Purpose

The cases are synthetically generated clinical cases produced by CliniProof and are being reviewed for clinical validity. Clinical validation uses a single review stage. Each clinician or resident reviews the complete case and assesses C1–C5 in one pass.

The frozen set is `CLINIPROOF_TAXONOMY_V1`, containing twenty-four cases labeled VAL-201 through VAL-224. That freeze is archived historical provenance and is not an active prospective study set. New reviewers should start at [`../../active_validation_sets.md`](../../active_validation_sets.md). Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation. That sentence means the software has already checked structure, terminology, and a limited set of implemented rules, but a clinician has not yet accepted the case for educational use.

## Reviewer task

For each case:

1. Read the complete case.
2. Assess C1–C5 using the forms that follow the case.
3. Record ratings in [`clinical_validation_worksheet.csv`](clinical_validation_worksheet.csv).
4. Add comments where a problem is identified.

Do not split these ratings across separate review stages. Complete all five criteria during this one review.

C1 asks whether the chart could reasonably represent a patient in the stated inpatient setting. C2 asks whether the intended medication-reconciliation or transition-of-care problem is actually present. C3 asks whether an internal medicine resident could detect and resolve that problem from the case documents. C4 asks whether another unintended clinically meaningful problem is also present. C5 is an expert estimate of expected learner difficulty.

This packet includes the intended assessment issue for each case so that C2 through C5 can be completed in the same pass as C1. Full criterion definitions are in [`validation_rubric.md`](validation_rubric.md).
"""

READABLE_INDEX_MD = """# Readable CliniProof review materials

This directory contains the human-readable review materials for the CliniProof freeze whose batch code is `CLINIPROOF_TAXONOMY_V1`. That freeze is **archived historical provenance** and is not an active prospective study set. New reviewers should start at [`../../active_validation_sets.md`](../../active_validation_sets.md). Clinical validation uses a single review stage. Each clinician or resident reviews the complete case and assesses C1–C5 in one pass.

The set contains twenty-four synthetic inpatient cases labeled VAL-201 through VAL-224. They were developed for assessment of medication-reconciliation reasoning. Twenty of the cases contain one pre-specified medication-reconciliation or transition-of-care assessment problem. Four of the cases are clean controls in which no problem was intentionally introduced. This page does not identify the controls.

These Markdown files are readable views of the frozen cases. They do not replace the frozen JSON, and they do not regenerate the underlying cases. Clinician-visible patient information comes from [`../resident_validation_cases.json`](../resident_validation_cases.json). The clinician validation packet also reads [`../investigator_answer_key.json`](../investigator_answer_key.json) so that C1–C5 can be completed together.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

To regenerate the Markdown from the repository root without modifying frozen JSON, run:

```bash
python scripts/build_readable_validation_packets.py --batch-code CLINIPROOF_TAXONOMY_V1 --resident data/validation/resident_validation_cases.json
```

This command regenerates the readable Markdown views only. It does not alter the frozen study cases.

## Where should I start?

A clinician or resident validating cases needs the packet and the worksheet. The other files are optional supporting material.

| Who is using it | File |
| --- | --- |
| Resident or clinician reviewing and rating cases | [`clinician_validation_packet.md`](clinician_validation_packet.md) |
| Resident or clinician recording ratings | [`clinical_validation_worksheet.csv`](clinical_validation_worksheet.csv) |
| Medical educator reviewing the validation criteria | [`validation_rubric.md`](validation_rubric.md) |
| Clinician or resident wanting to understand how CliniProof generates cases | [`how_cliniproof_works.md`](how_cliniproof_works.md) |
| Developer maintaining the pipeline | [`developer_notes.md`](developer_notes.md) |

## Clinician review files

[`clinician_validation_packet.md`](clinician_validation_packet.md) is the primary clinician-facing validation artifact. For each case it contains the readable chart, the intended assessment issue, and the C1–C5 forms. Record ratings on [`clinical_validation_worksheet.csv`](clinical_validation_worksheet.csv), which has one empty row per case.

Individual case pages under [`cases/`](cases/) and the sequential chart dump [`all_cases.md`](all_cases.md) are supporting readable views of the same frozen cases. They do not include the intended assessment issue or rating forms, and they are not a separate review stage.

## Machine validation is not clinical validation

The software performs automated checks of structure, terminology provenance, implemented clinical constraints, and the intended assessment manipulation. Those checks do not establish that a case is clinically realistic or educationally appropriate. Human reviewers make that determination by completing C1–C5 in one pass.
"""

VALIDATION_RUBRIC_MD = """# CliniProof Clinical Case Validation Rubric

## Purpose

A clinician or resident evaluates each synthetic inpatient case in a single review before it is accepted for use. Clinical validation uses a single review stage. Each reviewer reads the complete case and assesses C1–C5 in one pass.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation. The frozen set is identified by its batch code in this directory. Active prospective sets are `CLINIPROOF_BALANCED_V4` and `CLINIPROOF_SEEDCASES_V3`. `CLINIPROOF_TAXONOMY_V1` is archived historical provenance.

The five criteria serve different purposes and should not be collapsed into a single pass or fail judgment. C2 through C4 are required: if any of them fails, the case cannot be used against its intended answer key until it is revised or excluded. C5 is advisory and must not by itself cause a case to fail validation.

The taxonomy also defines required companion medication omitted (`f2_coprescription_omitted`), which represents a situation in which a clinically required companion medication is missing. This category is not included in the current validation sets because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing or encoding an unsupported rule, the system currently rejects this category.

## C1 — Clinical plausibility

### Clinical question

Could this reasonably represent a patient encountered in the stated inpatient clinical setting?

### Reviewer should look for

Reviewers rate the following eight domains from the clinical chart:

1. Presentation and demographics
2. Fit between presentation and diagnosis
3. Vital signs
4. Laboratory findings
5. Medication regimen
6. Hospital course
7. Consistency across the chart
8. Discharge plan and follow-up

Clinical plausibility is not the same as optimal management or complete guideline concordance. Unusual but source-backed formulations or units should be recorded if they undermine credibility. They should not be silently corrected in the frozen case.

### Scale for each domain

A rating of 1 means implausible. A rating of 2 means questionable and requires revision. A rating of 3 means plausible with minor concern. A rating of 4 means fully plausible.

Any domain rated 1 or 2 must include a written explanation that identifies the specific clinical concern.

Reviewers also answer the overall question: could this reasonably represent a patient encountered in the stated inpatient clinical setting? The allowed answers are Yes or No.

### Result

C1 passes when all clinically relevant domains are rated 3 or 4 and the overall clinical plausibility answer is Yes.

If any domain is rated 1 or 2, or if the overall answer is No, record that revision is needed for clinical plausibility.

C1 is completed in the same review as C2 through C5.

### Technical interpretation

C1 is a clinical-realism judgment on the chart. Software already checked schema, terminology identifiers, and implemented rules. C1 asks whether a physician still finds the chart coherent.

## C2 — Intended assessment problem

### Clinical question

Does the case actually contain the medication-reconciliation or transition-of-care problem it was designed to assess?

### Reviewer should look for

Determine whether the intended problem is present, whether it matches the intended category, and whether the investigator description accurately reflects the clinical case.

### Result

Record Pass or Fail. C2 is a hard requirement. If C2 fails, the case cannot be used against its intended answer key until the problem is corrected or the case is excluded. A written explanation is required for a failure.

### Technical interpretation

This criterion checks fidelity of the deterministic injection to the planned standardized category. The planned category, the injected kind, and the answer-key category must describe the same visible target.

## C3 — Detectability

### Clinical question

Could an internal medicine resident identify and resolve the intended problem using only the clinical information provided in the case?

### Reviewer should look for

Consider whether all necessary evidence is available, whether important information is missing, whether the case is ambiguous, and whether wording or formatting gives away the answer. For Family 2, the trigger or precondition must be visible and unambiguous.

### Result

Record Pass or Fail. C3 is a hard requirement. A written explanation is required for a failure.

### Technical interpretation

This corresponds to evidentiary sufficiency and cue integrity in the CliniProof assessment model. The resident export must be sufficient without investigator fields.

## C4 — Absence of unintended problems

### Clinical question

Apart from the intended assessment problem, does the case contain another clinically meaningful medication-reconciliation or transition-of-care problem?

### Reviewer should look for

Reviewers must actively search for additional problems. This is not simply a record of problems that happen to be noticed. After reviewing the complete case, ask whether another clinically meaningful discrepancy is present that a reasonable resident could interpret as an assessment target.

### Result

Record Pass or Fail. C4 is a hard requirement. If the result is Fail, identify the additional problem, the medication or clinical issue involved, and why it is clinically meaningful.

### Technical interpretation

Error isolation means exactly one intended assessment target on error-bearing cases and zero on clean controls. An unintended second target makes the answer key unusable.

## C5 — Expected learner difficulty

### Clinical question

How difficult would this case likely be for an internal medicine resident?

### Reviewer should look for

Provide a provisional expert estimate using Easy, Moderate, Hard, or Inappropriate / outlier.

This is an expert estimate of difficulty. Actual difficulty should ultimately be determined from resident performance.

### Result

C5 is advisory. It should not by itself cause a case to fail validation.

### Technical interpretation

Any prior difficulty field in the answer key is optional metadata, not a software-computed score.

## Family-specific guidance for C2 through C4

Criteria C2 through C4 must account for different clinical structures. Family 1 problems generally involve comparing home, inpatient, and discharge medication lists. Family 2 problems may leave those lists unchanged and instead omit a required transition action.

### Family 1 — medication-list and transition discrepancies

#### Medication omitted at discharge (`f1_omission`)

A medication intended to continue after hospitalization is absent from the discharge medication list without a documented reason.

#### Medication inappropriately added or continued (`f1_commission`)

A medication that should not be on the discharge list, for example one that was held or stopped, appears there without a documented decision to continue it.

#### Unexplained dose discrepancy (`f1_dose_mismatch`)

The discharge dose differs from the intended continued dose without an explanation.

#### Unexplained route discrepancy (`f1_route_mismatch`)

The discharge route differs from the intended continued route without an explanation.

#### Unexplained frequency discrepancy (`f1_frequency_mismatch`)

The discharge frequency differs from the intended continued frequency without an explanation.

#### Unexplained therapeutic substitution (`f1_therapeutic_substitution`)

The discharge list replaces an intended continued medication with another agent of the same class without documenting an intentional switch.

### Family 2 — transition-of-care gaps

These problems may involve absence of monitoring, follow-up, supply, restart planning, or another transition action. Do not identify Family 2 solely by comparing medication lists. For Family 2, the trigger or precondition must be visible, and the missing companion action is the specified target.

#### Required outpatient monitoring not arranged (`f2_monitoring_not_arranged`)

Warfarin is continued at discharge, but outpatient INR monitoring has not been arranged. In CliniProof this is classified as a Family 2 transition-of-care gap because the medication order itself remains unchanged; the missing element is the required follow-up action.

#### Held medication without a restart plan (`f2_held_med_no_restart_plan`)

A home medication is intentionally held in the hospital for a legitimate temporary reason, but discharge documentation does not say when or under what conditions it should be resumed.

#### Insufficient medication supply (`f2_insufficient_supply`)

Days’ supply at discharge is too short to last until the planned follow-up. The medication identity on the list may be correct; the missing element is enough supply to bridge to the next visit.

#### Hospital-only medication continued after discharge (`f2_hospital_only_continued`)

A medication started for an inpatient-only indication is still on the discharge list. Reviewers should notice that a hospital-only product was not stopped at the transition home.

#### Temporary inpatient substitution not addressed at discharge (`f2_inpatient_substitution_not_reverted`)

A temporary inpatient substitute was used, but discharge does not revert to home therapy or document an intentional decision to continue the substitute.

#### Follow-up missing for an unresolved treatment decision (`f2_pending_decision_followup_missing`)

A treatment decision was left pending, but no follow-up is arranged to resolve it. The medication list may look intact, but the chart does not say when or by whom the unresolved decision will be revisited.

#### Required companion medication omitted (`f2_coprescription_omitted`)

The taxonomy also defines this category for a situation in which a clinically required companion medication is missing. This category is not included in the current validation sets because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing or encoding an unsupported rule, the system currently rejects this category.

## Reviewer recommendation

After completing C1–C5 in the same review, record one recommendation.

☐ Accept

☐ Revise

☐ Exclude

Accept means the case is suitable for use without clinically meaningful revision. Revise means the case requires one or more changes before it should be used. Exclude means the case should not be used in the validation set because its problems cannot be reasonably corrected without substantially reconstructing it.

If revision is requested:

### Recommended revision

____________________________________

### Clinical reason for revision

____________________________________

Recommended revisions are required whenever Revise is selected. Examples may include changing an implausible formulation, clarifying the hospital course, correcting an unrealistic laboratory unit, adding information needed to detect the intended problem, or removing an unintended second discrepancy.

Do not automatically modify a case based on reviewer comments. Human review comments are recommendations that must be considered by the study team. Do not overwrite frozen case files during human review. Reviewer comments and revision requests should be stored separately.
"""

HOW_CLINIPROOF_WORKS_MD = """# How CliniProof Builds and Validates a Case

This overview is for residents who are curious about the technology, physicians, medical educators, pharmacists, informatics staff, and AI engineers. It explains the system in clinical language first, then names the software pieces. It is not required reading before completing C1–C5.

It discusses how cases are made. It does not reveal which frozen case contains which assessment target.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

## A. Clinical overview

CliniProof creates synthetic inpatient medication-reconciliation cases with a known assessment target.

Medication reconciliation is the clinical work of making a best-possible medication history, comparing it with inpatient orders and the discharge list, and ensuring that holds, stops, continuations, substitutions, supplies, monitoring, and follow-up are explicit and safe.

Some cases are clean controls. In those charts the software leaves the encounter without an intentionally planted assessment problem, so reviewers and residents can also see an intact reconciliation. Other cases receive exactly one planned problem after the clean chart has already passed automated checks. Four of the twenty-four frozen cases are clean controls. They are included so that residents cannot assume that every case necessarily contains an error. This document does not say which identifiers are controls.

Family 1 problems, recorded in software as `family_1`, are discrepancies on the medication lists themselves: a drug missing at discharge, an extra drug, or an unexplained change in dose, route, frequency, or product.

Family 2 problems, recorded as `family_2`, are transition-of-care gaps. The discharge medication identity may be unchanged; what is missing is a required companion action such as INR monitoring, a restart plan for a held drug, enough days’ supply, stopping a hospital-only drug, reverting a temporary substitute, or arranging follow-up for an unresolved decision.

Do not identify Family 2 solely by comparing home versus discharge lists.

### Implemented categories

Each category has a clinical name and a standardized identifier used in software and investigator materials. The current dataset uses the canonical CliniProof taxonomy. The identifier is shown in parentheses after the clinical name.

#### Family 1

##### Medication omitted at discharge (`f1_omission`)

A medication intended to continue after hospitalization is absent from the discharge medication list without a documented reason. This is a Family 1 medication-transition discrepancy. The clean expected discharge medication is present before assessment modification and removed from the final discharge list.

##### Medication inappropriately added or continued (`f1_commission`)

A medication that should not continue, for example one held or stopped, appears on the discharge list. The injector adds or retains a discharge-list entry that the clean case had omitted for a documented reason.

##### Unexplained dose discrepancy (`f1_dose_mismatch`)

The discharge dose differs from the intended continued dose without a documented explanation. This is a Family 1 medication-list discrepancy. After the clean case passes validation, the injector changes only the dose field on the discharge entry. Home and inpatient lists remain unchanged so that a reviewer can see the intended dose.

##### Unexplained route discrepancy (`f1_route_mismatch`)

The discharge route differs from the intended continued route without a documented explanation. For example, an oral medication might appear as a different route at discharge with no rationale in the chart.

##### Unexplained frequency discrepancy (`f1_frequency_mismatch`)

The discharge frequency differs from the intended continued frequency without a documented explanation. For example, a once-daily medication might appear as twice daily at discharge, or the reverse.

##### Unexplained therapeutic substitution (`f1_therapeutic_substitution`)

The discharge list shows a same-class substitute instead of the intended continued product, without documenting an intentional switch. The original product remains visible on the home or inpatient list so that the substitution can be noticed.

#### Family 2

##### Required outpatient monitoring not arranged (`f2_monitoring_not_arranged`)

Warfarin is continued at discharge, but outpatient INR monitoring has not been arranged. In CliniProof this is classified as a Family 2 transition-of-care gap because the medication order itself remains unchanged; the missing element is the required follow-up action. After the clean case passes validation, the injector removes the expected monitoring record. The medication itself remains unchanged.

##### Held medication without a restart plan (`f2_held_med_no_restart_plan`)

The original medication is intentionally stopped during hospitalization for a legitimate temporary reason, but the discharge documentation does not tell the patient or outpatient clinician when or under what conditions it should be resumed. The hold itself remains visible; what is missing is the restart plan.

##### Insufficient medication supply (`f2_insufficient_supply`)

Days’ supply at discharge is shortened so that treatment cannot last until the planned follow-up. The medication identity on the discharge list may be correct; the missing element is enough supply to bridge to the next visit.

##### Hospital-only medication continued after discharge (`f2_hospital_only_continued`)

A drug started for an inpatient-only indication remains on the discharge list. Reviewers are expected to notice that a hospital-only product was not stopped at the transition home.

##### Temporary inpatient substitution not addressed at discharge (`f2_inpatient_substitution_not_reverted`)

A temporary inpatient substitute is left in place without reverting to home therapy or documenting an intentional decision to continue the substitute.

##### Follow-up missing for an unresolved treatment decision (`f2_pending_decision_followup_missing`)

A pending therapeutic decision has no arranged follow-up. The medication list may look intact, but the chart does not say when or by whom the unresolved decision will be revisited.

##### Required companion medication omitted (`f2_coprescription_omitted`)

The taxonomy also defines this category for a situation in which a clinically required companion medication is missing. This category is not included in the current validation sets because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing or encoding an unsupported rule, the system currently rejects this category.

## B. Source-backed versus synthetic information

A source-backed concept is not the same thing as real patient data. An RxNorm identifier for warfarin means the concept came from RxNorm, not that a real patient was taking warfarin.

The table below separates the kinds of information that appear on a case. Official vocabulary rows are retrieved from terminology services. Patient-specific numbers and stories are generated. Assessment discrepancies are introduced only after the clean chart has passed automated checks.

| Type of information | Example | How it is obtained |
| --- | --- | --- |
| Medication concept | Warfarin | Retrieved from RxNorm |
| Diagnosis concept | Heart failure | Retrieved from ICD-10-CM |
| Laboratory test | Creatinine | Retrieved from LOINC |
| Unit | mmol/L | Retrieved from UCUM or LOINC |
| Age | 72 | Synthetically generated |
| Blood pressure | 128/74 | Synthetically generated |
| Lab result | Creatinine 1.3 | Synthetic patient value |
| Clinical narrative | History of present illness | Template sentences, or optional LLM wording of already selected facts |
| Assessment discrepancy | Missing monitoring | Introduced deterministically after clean validation |

Official source ranking can yield technically valid but clinically atypical formulations or units, for example a solution or gel, or an SI laboratory unit. Those oddities are left visible for clinician review. They are not silently rewritten.

## C. Generation pipeline

Cases are built in a fixed order. Each stage completes before the next stage begins.

1. A clinical scenario is selected. A clinical scenario is an inpatient teaching skeleton chosen by an operator. It specifies specialty, age band, diagnosis and medication search phrases, and which assessment categories are allowed.
2. Terminology is resolved. Search phrases are matched to identifiers already stored from official services, including RxNorm, ICD-10-CM, LOINC, UCUM, and related sources. The generator does not invent codes.
3. A clean synthetic patient is assembled: demographics, vital signs, laboratory values, medication lists, notes, and follow-up, internally consistent with the scenario and the stored concepts.
4. Rule checks apply a small set of source-backed if-then constraints, and only those with attached DailyMed or RxClass evidence. This is not a complete clinical guideline.
5. Clean validation checks structure, confirms that every coded concept exists in local reference tables, confirms that hard rules hold, and confirms that the clean chart does not already contain the assessment target that would later be planted.
6. Assessment target eligibility asks whether the planned category can actually be applied to this case. If not, generation stops. Another category is not silently substituted.
7. Controlled error introduction applies exactly one planned change for assessment cases. Clean controls skip this step.
8. Post-error validation checks that the intended target is now present, that required evidence remains visible, and that a second assessment target was not introduced.
9. Blinded resident export gives residents the chart without family, category, trigger metadata, or answer keys.
10. Clinician validation is the human step. A clinician or resident reviews the complete case and assesses C1–C5 in one pass. Ratings are recorded on the clinical validation worksheet. Automated checks cannot certify realism or educational appropriateness.

## D. What OpenAI does

OpenAI is optional in the CliniProof pipeline and is used only to help word narrative text from clinical facts that have already been selected by the structured generator. It does not choose diagnoses, medications, terminology codes, error categories, clinical rules, or answer-key content.

The committed prospective validation sets use template narrative rather than OpenAI. The freeze command sets the OpenAI flag to false.

Raw patient-source rows are never sent to a language model.

## E. Why machine validation is not clinical validation

The software performs automated checks of structure, terminology provenance, implemented clinical constraints, and the intended assessment manipulation. These checks are useful for detecting technical inconsistencies, but they do not establish that a case is clinically realistic, educationally appropriate, or representative of actual practice. Those judgments require review by clinicians.

Until clinicians finish review, every generated record remains a machine-validated synthetic resident-review case pending clinician validation.

## F. Technical implementation

Physicians can stop here. The table below is for engineers and informatics staff. It names the repository files that implement each function already described in clinical language.

| Function | Implementation |
| --- | --- |
| Scenario definitions | `data/bootstrap/scenarios.json` |
| Terminology bootstrap | `app/services/bootstrap.py` |
| Case generation | `app/services/generation.py` |
| Error taxonomy | `app/services/error_taxonomy.py` |
| Error injection | `app/services/error_injection.py` |
| Validation | `app/services/validation.py` |
| Freeze/export | `app/services/validation_batch.py` |
| Optional narrative LLM | `app/openai/narrative.py` |
| Readable Markdown views | `app/services/readable_packets.py` |

Standardized families are Family 1 (`family_1`), Family 2 (`family_2`), and no planted target (`none`) for a clean control. Standardized categories are the `f1_*` and `f2_*` identifiers listed above. Unknown names fail rather than being aliased.

Readable packets are regenerated with an explicit `--batch-code` and `--resident` path, for example `python -m app.services.readable_packets --batch-code CLINIPROOF_BALANCED_V4 --resident data/validation_balanced_v4/resident_validation_cases.json` or `--batch-code CLINIPROOF_SEEDCASES_V3 --resident data/validation_seedcases_v3/resident_validation_cases.json`, and do not rewrite frozen JSON.
"""

DEVELOPER_NOTES_MD = """# CliniProof Implementation Notes for Clinical Informatics and AI Engineering

This note assumes you understand software engineering and may not have a clinical training background. It translates the medical objective into the modules that implement it.

It explains mechanisms. It does not map any frozen identifier to a hidden assessment target. That mapping exists only in investigator-only files.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

## Clinical objective

Hospitals reconcile medications at admission and discharge so that intended home therapy is neither dropped nor continued unsafely, and so that required monitoring and follow-up actually occur.

CliniProof builds synthetic inpatient charts for that task. Each assessment item has a known target chosen before generation, not discovered afterwards by a model. Residents see a chart. Investigators see the target. Human clinicians still decide whether the chart is believable enough to use.

## Why canonical vocabularies are used

If the case said only “a heart-failure pill,” reviewers could not tell which product was meant, and software could not check rules. Official vocabularies give citable identifiers. RxNorm identifiers (RXCUI) name medications. ICD-10-CM codes name diagnoses. LOINC codes name laboratory tests. UCUM codes name units.

Those identifiers are stored only after an official service returns them, together with provenance fields for the source system, source version, and retrieval time. The generator never invents a code. SNOMED CT is not ingested here; SNOMED fields stay empty rather than being fabricated.

## Source-backed versus synthetic

The table below is the same distinction clinicians need, restated for engineers. A source-backed warfarin concept is not evidence that a real patient was taking warfarin.

| Layer | Meaning |
| --- | --- |
| Source-backed concept | The type of thing, such as warfarin as an RxNorm identifier or creatinine as a LOINC test, came from an official terminology |
| Synthetic value | The patient-specific number or story, such as age 72, creatinine 1.3, or the history-of-present-illness sentences, was generated |
| Deterministic assessment change | After the clean chart passed checks, software applied one planned edit |

## Scenario structure

The file `data/bootstrap/scenarios.json` holds teaching skeletons: specialty, age band, search phrases for diagnoses, symptoms, medications, and labs, and which standardized assessment categories are allowed. Matching happens against already bootstrapped reference rows in `app/services/bootstrap.py`, not against live free text.

## Clean-case concept

Generation in `app/services/generation.py` first builds a clean structured encounter: demographics, presentation, medications in three contexts (home, inpatient, and discharge), labs, vitals, notes, monitoring, follow-up, and instructions. Clean means the chart should not already contain the assessment target that the plan might later introduce.

A small rules engine in `app/services/rules.py` applies only conditionals that have attached DailyMed or RxClass evidence. There are few such rules. They are not a complete specialty guideline.

## Family 1 versus Family 2

Identifiers live in `app/services/error_taxonomy.py`.

Family 1 (`family_1`) means the discharge list is wrong relative to intended continuation. The following table lists the clinical meaning first and the software identifier second.

| Clinical meaning | Identifier |
| --- | --- |
| Medication omitted at discharge | `f1_omission` |
| Medication inappropriately added or continued | `f1_commission` |
| Unexplained dose discrepancy | `f1_dose_mismatch` |
| Unexplained route discrepancy | `f1_route_mismatch` |
| Unexplained frequency discrepancy | `f1_frequency_mismatch` |
| Unexplained therapeutic substitution | `f1_therapeutic_substitution` |

Family 2 (`family_2`) means a required transition action is missing; the continued-drug identity may be unchanged.

| Clinical meaning | Identifier |
| --- | --- |
| Required outpatient monitoring not arranged | `f2_monitoring_not_arranged` |
| Held medication without a restart plan | `f2_held_med_no_restart_plan` |
| Insufficient medication supply | `f2_insufficient_supply` |
| Hospital-only medication continued after discharge | `f2_hospital_only_continued` |
| Temporary inpatient substitution not addressed at discharge | `f2_inpatient_substitution_not_reverted` |
| Follow-up missing for an unresolved treatment decision | `f2_pending_decision_followup_missing` |
| Required companion medication omitted | `f2_coprescription_omitted` |

Held medication without a restart plan means the original medication is intentionally stopped during hospitalization for a legitimate temporary reason, but the discharge documentation does not tell the patient or outpatient clinician when or under what conditions it should be resumed. That maps to `f2_held_med_no_restart_plan`.

Required outpatient monitoring not arranged means, for example, warfarin continues at discharge but outpatient INR monitoring was not scheduled. That maps to `f2_monitoring_not_arranged`. The medication row stays; the monitoring record is what changes.

The taxonomy also defines required companion medication omitted (`f2_coprescription_omitted`). This category is not included in the current validation sets because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing, freeze currently rejects this category.

Do not implement Family 2 detection as a simple difference of the three medication lists.

## Eligibility, injection, and no fallback

The freeze plan names the error family and error category before generation in that batch’s `batch_plan.json`.

The taxonomy module in `app/services/error_taxonomy.py` decides whether the clean case is eligible for that category. For example, there must be a continued discharge drug to omit, or a monitoring-dependency rule must match.

The injector in `app/services/error_injection.py` then applies the exact edit, or skips injection for a clean control whose category is `none`.

If the category is unknown, ineligible, or marked `not_yet_implementable`, freeze aborts. It does not pick a different error. A language model never chooses the category.

## Clean state and injected state

The investigator answer key stores both states. The clean expected state is what the field was after clean validation, for example the omitted drug present on the discharge list. The injected state is what residents see after the edit, for example absent.

Residents must not receive these fields. The readable investigator packet is the human view of the same concealed specification.

## Machine validation

Validation in `app/services/validation.py` and freeze-time checks in `app/services/validation_batch.py` cover structure, terminology integrity, implemented rules, category eligibility, the expected state transition, answer-key consistency, isolation of a second target, and leak checks on the resident export.

The software performs automated checks of structure, terminology provenance, implemented clinical constraints, and the intended assessment manipulation. These checks are useful for detecting technical inconsistencies, but they do not establish that a case is clinically realistic, educationally appropriate, or representative of actual practice. Those judgments require review by clinicians.

## Resident blinding

The resident JSON omits answer-key objects, internal generation identifiers, family and category fields, trigger metadata, and clean or injected state. Readable files `all_cases.md` and the individual case pages are derived only from that blinded export.

## Human clinician validation

Human validation of the frozen set uses a single review stage. A clinician or resident reads the complete case in `clinician_validation_packet.md` and assesses C1–C5 in one pass. Ratings are stored on `clinical_validation_worksheet.csv`. Reviewer comments do not rewrite frozen JSON.

Case generation and automated checks remain unchanged. Software checks structure, terminology, implemented rules, and the intended assessment manipulation. Those checks do not replace this human review.

## Freeze immutability and provenance

Frozen files for batch `CLINIPROOF_TAXONOMY_V1` under `data/validation/` are archived historical provenance. Regenerating live terminology from APIs is not expected to reproduce bit-identical JSON. Readable Markdown is allowed to be regenerated from those frozen files; the frozen files themselves must not be rewritten to improve clinical content.

Each frozen assignment records scenario, seed, family, category, source-version snapshots, and validation statuses in the investigator key and manifest.

## Optional narrative language model

The module `app/openai/narrative.py` may reword admission prose from already chosen names. It is not a case generator. OpenAI is optional in the CliniProof pipeline and is used only to help word narrative text from clinical facts that have already been selected by the structured generator. It does not choose diagnoses, medications, terminology codes, error categories, clinical rules, or answer-key content. The committed freeze used templates only.

## Reproducing the pipeline

Operators who already have a database and terminology bootstrap can run the following commands. Pass an explicit `--plan` and `--batch-code`. Do not re-freeze expecting to replace archived VAL-201 through VAL-224. To refresh clinician-facing Markdown only, run the readable-packet script with `--batch-code`.

```bash
clinical-case-generator db-init
clinical-case-generator bootstrap-reference-data
clinical-case-generator freeze-validation-batch --plan data/validation_balanced_v3/batch_plan.json
clinical-case-generator export-validation-batch --batch-code CLINIPROOF_BALANCED_V4
python -m app.services.readable_packets --batch-code CLINIPROOF_BALANCED_V4 --resident data/validation_balanced_v4/resident_validation_cases.json
clinical-case-generator export-validation-batch --batch-code CLINIPROOF_SEEDCASES_V3
python -m app.services.readable_packets --batch-code CLINIPROOF_SEEDCASES_V3 --resident data/validation_seedcases_v3/resident_validation_cases.json
```
"""
