"""Static Markdown for derived CliniProof clinician/technical packets.

These strings are copied into data/validation/readable/ by the generator.
They discuss mechanisms generically and must not map a VAL ID to a hidden target.
"""

from __future__ import annotations

ABOUT_CASE_DATA = """## About the case data

This is a synthetic case created for medication-reconciliation assessment. It is not an extract from an individual patient’s medical record.

Medication names, diagnoses, and laboratory tests are drawn from established clinical terminology sources so that the concepts can be cited. Patient-specific values such as age, vital signs, and numeric laboratory results, and the surrounding clinical scenario, are generated by the software.

The case has undergone automated checks for structure, terminology consistency, and the implemented clinical constraints. Those checks can detect technical inconsistencies, but they do not establish that the case is clinically realistic, educationally appropriate, or ready for use without clinician review.
"""

ALL_CASES_HEADER = """# CliniProof Clinical Case Set

## CLINIPROOF_TAXONOMY_V1

This document is intended for residents, clinicians, medical educators, pharmacists, and clinical informatics collaborators who want to review the clinical cases without reading the underlying JSON representation.

The set contains twenty-four cases, labeled VAL-201 through VAL-224. Each case is a synthetic inpatient encounter assembled for medication-reconciliation review. The software has already checked structure, terminology provenance, and a limited set of implemented clinical rules. Those automated checks do not establish clinical validity. Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

This file contains only the information a resident would see. It does not identify which cases contain an intended assessment problem, if any, and it does not include investigator answer keys.

## How these cases are created

These cases are synthetic rather than extracted from individual patient records.

Clinical concepts such as medication names, diagnoses, and laboratory tests are linked to established terminology sources. Patient-specific values such as age, vital signs, and laboratory results are generated by the software.

The system first creates a structured case and checks its terminology, internal structure, and a limited set of predefined clinical rules. For assessment cases, a specific medication-reconciliation problem may then be introduced in a controlled way. Some cases are left unchanged as clean controls so that a reviewer cannot assume that every chart necessarily contains an error. This file does not say which cases are controls. Human clinician review is required because automated checks cannot establish that a case is clinically realistic or educationally appropriate.

The construction sequence is as follows.

1. A clinical scenario is selected, for example an inpatient heart-failure or pneumonia theme.
2. Medication, diagnosis, and laboratory concepts are resolved against established terminology sources that have already been stored locally.
3. A synthetic patient encounter is constructed, including demographics, vital signs, laboratory values, medication lists, notes, and follow-up.
4. Automated clinical and structural checks are applied to that clean case.
5. For assessment cases, a predefined medication-reconciliation problem may be introduced. Clean controls skip this step.
6. The case is checked again after any assessment modification.
7. Resident-facing and investigator-facing versions are separated. Residents receive the chart. Investigators receive the concealed assessment target separately.
8. Clinicians review the resulting cases before educational use.

Medication reconciliation, in ordinary clinical terms, is the process of comparing what the patient was taking before admission, what was given in the hospital, and what is prescribed at discharge, then ensuring that intended continuations, holds, stops, supplies, monitoring, and follow-up actions are explicit.

Review each case as you would a discharge chart. Ask whether the patient story is coherent, and whether you can complete a careful medication-reconciliation review from the documents provided.
"""

PLAUSIBILITY_HEADER = """# CliniProof clinical-plausibility packet

## CLINIPROOF_TAXONOMY_V1

This is Stage 1 of independent dual expert review with structured consensus resolution. Both clinical reviewers complete this section independently before seeing the intended assessment target.

The packet contains only the resident-visible version of each case. It does not reveal whether a case is a clean control, the intended error family, the intended error category, the medication targeted by the assessment, the correct action, or any other answer-key field.

Both reviewers independently complete Criterion 1 (C1). The purpose is to assess the clinical credibility of the case without being influenced by knowledge of the intended assessment problem. C1 ratings must be submitted and locked before either reviewer opens the investigator packet.

These cases are synthetic rather than extracted from individual patient records. Clinical concepts such as medication names, diagnoses, and laboratory tests are linked to established terminology sources. Patient-specific values such as age, vital signs, and laboratory results are generated by the software.

When you rate C1, ask whether this chart could reasonably represent a patient encountered in the stated inpatient clinical setting. Clinical plausibility is not the same as optimal management or complete guideline concordance. Comment on the exact field or issue for any domain rated 1 or 2.

Do not record Accept, Revise, or Exclude on this form. Those recommendations are made only after Stage 2, when C2 through C5 have also been completed.

Full criterion definitions are in [`validation_rubric.md`](validation_rubric.md). The two-reviewer workflow is in [`reviewer_protocol.md`](reviewer_protocol.md).

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.
"""

INVESTIGATOR_HEADER = """# Investigator / Clinical Validator Copy

This document contains the intended assessment target for each case. Reviewers should complete and submit the blinded C1 plausibility review before using this packet.

**INVESTIGATOR / VALIDATOR ONLY — DO NOT DISTRIBUTE TO RESIDENT PARTICIPANTS**

This is Stage 2 of independent dual expert review with structured consensus resolution. After both reviewers have submitted and locked their C1 ratings, they receive this packet and independently evaluate C2 through C5, then record Accept, Revise, or Exclude. Original independent C1 ratings remain unchanged.

Each case appears in two parts after the reminder above. First is the resident-visible clinical chart, which is the same content residents see. Second is the intended assessment issue, written with a clinical label and the standardized CliniProof identifier, followed by the C2 through C5 forms and the independent recommendation.

Do not record consensus on this independent form. After both reviewers have submitted, compare ratings and, when needed, complete structured consensus review on [`consensus_worksheet.csv`](consensus_worksheet.csv). Consensus does not overwrite the original independent ratings.

The rating criteria are defined in [`validation_rubric.md`](validation_rubric.md). The two-reviewer workflow is in [`reviewer_protocol.md`](reviewer_protocol.md).

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.
"""

READABLE_INDEX_MD = """# Readable CliniProof review materials

These files are derived human-readable views of the frozen CliniProof validation set whose batch code is `CLINIPROOF_TAXONOMY_V1`. That set contains twenty-four cases labeled VAL-201 through VAL-224. The Markdown views do not replace the frozen JSON, and they do not regenerate the underlying cases. They were generated by `scripts/build_readable_validation_packets.py` from two sources. Clinician-visible patient information comes from [`../resident_validation_cases.json`](../resident_validation_cases.json). The investigator packet additionally reads [`../investigator_answer_key.json`](../investigator_answer_key.json).

The twenty-four-case validation set will undergo independent dual expert review with structured consensus resolution. Two clinical reviewers first assess clinical plausibility while blinded to the intended assessment target. After submitting those ratings, they review the concealed target and independently evaluate error fidelity, detectability, absence of unintended problems, and expected learner difficulty. Cases with important disagreements undergo structured consensus review. Original independent ratings are preserved.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

To regenerate the Markdown from the repository root without modifying frozen JSON, run:

```bash
python scripts/build_readable_validation_packets.py
```

## Where should I start?

The table below routes different readers to the file that matches their task. Residents and plausibility reviewers should stay on the resident-safe files. Only investigators and expert validators should open the concealed-target packet.

| If you are... | Start here |
| --- | --- |
| Resident or clinician reviewing cases | [`all_cases.md`](all_cases.md) |
| Clinical reviewer completing Stage 1 (blinded C1) | [`plausibility_only_packet.md`](plausibility_only_packet.md) |
| Clinical reviewer completing Stage 2 (C2–C5) | [`clinician_validation_packet.md`](clinician_validation_packet.md) |
| Clinical reviewer reading the two-reviewer protocol | [`reviewer_protocol.md`](reviewer_protocol.md) |
| Medical educator reviewing the framework | [`validation_rubric.md`](validation_rubric.md) |
| Recording independent ratings (empty template) | [`clinical_validation_worksheet.csv`](clinical_validation_worksheet.csv) |
| Recording consensus (empty template) | [`consensus_worksheet.csv`](consensus_worksheet.csv) |
| Clinician or resident curious how CliniProof works | [`how_cliniproof_works.md`](how_cliniproof_works.md) |
| Clinical informatics / AI engineer | [`developer_notes.md`](developer_notes.md) |

## Safe for residents and plausibility-only review

The files listed here contain resident-visible case content and generic explanations of how cases are made. They do not include planted-error family, category, trigger labels, control status, or per-case answer keys.

| File | Contents |
| --- | --- |
| [`all_cases.md`](all_cases.md) | All twenty-four readable cases, presented sequentially |
| [`plausibility_only_packet.md`](plausibility_only_packet.md) | Each readable case followed by the Stage 1 C1 form |
| [`cases/`](cases/) | One page per case, VAL-201 through VAL-224 |
| [`how_cliniproof_works.md`](how_cliniproof_works.md) | Clinical-to-technical overview with no per-case answers |
| [`developer_notes.md`](developer_notes.md) | Informatics and engineering notes that describe mechanisms only |
| [`validation_rubric.md`](validation_rubric.md) | The C1 through C5 rubric with no per-case answers |
| [`reviewer_protocol.md`](reviewer_protocol.md) | Two-reviewer independent dual expert review protocol |
| [`clinical_validation_worksheet.csv`](clinical_validation_worksheet.csv) | Empty independent-rating template; no ratings are pre-filled |
| [`consensus_worksheet.csv`](consensus_worksheet.csv) | Empty consensus-outcome template, stored separately from independent ratings |

## Investigator / validator only

The following file associates each VAL identifier with its intended assessment target. Do not provide it to resident study participants. Reviewers should complete Stage 1 C1 before opening it.

| File | Contents |
| --- | --- |
| [`clinician_validation_packet.md`](clinician_validation_packet.md) | Readable case, concealed target, C2 through C5 forms, and independent recommendation |
"""

VALIDATION_RUBRIC_MD = """# CliniProof Clinical Case Validation Rubric

## Purpose

Two clinical reviewers independently evaluate each synthetic inpatient case before it is accepted for use in the resident assessment. The study method is independent dual expert review with structured consensus resolution. It is not a Delphi process.

Review proceeds in two stages.

1. Blinded clinical plausibility review. Both reviewers first receive only the resident-visible version of each case. They do not see whether the case is a control, the intended error family, the intended error category, the medication targeted by the assessment, the correct action, or any other answer-key field. They independently complete Criterion 1 (C1). Those ratings are submitted and locked before Stage 2 begins.
2. Assessment-target validation. After C1 ratings are locked, both reviewers receive the investigator packet that names the intended assessment target. They then independently complete Criteria C2 through C5 and record an overall recommendation of Accept, Revise, or Exclude.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation. The frozen set is `CLINIPROOF_TAXONOMY_V1`, containing cases VAL-201 through VAL-224.

The five criteria serve different purposes and should not be collapsed into a single pass or fail judgment. C1 can be completed from the resident-visible chart alone. C2 through C4 are hard requirements: if any of them fails, the case cannot be used against its intended answer key until it is revised or excluded. C5 is advisory and must not by itself cause a case to fail validation.

The taxonomy also defines required companion medication omitted (`f2_coprescription_omitted`), which represents a situation in which a clinically required companion medication is missing. This category is not included in the current validation set because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing or encoding an unsupported rule, the system currently rejects this category.

## C1 — Clinical plausibility

### Clinical question

Could this reasonably represent a patient encountered in the stated inpatient clinical setting?

### Reviewer should look for

Both reviewers independently rate the following eight domains from the resident-visible chart only:

1. Presentation and demographics
2. Fit between presentation and diagnosis
3. Vital signs
4. Laboratory findings
5. Medication regimen
6. Hospital course
7. Consistency across the chart
8. Discharge plan and follow-up

Clinical plausibility is not the same as optimal management or complete guideline concordance. Unusual but source-backed formulations or units should be recorded if they undermine credibility. They should not be silently corrected in the frozen case.

### Scale for each domain

A rating of 1 means implausible. A rating of 2 means questionable and requires revision. A rating of 3 means plausible with minor concern. A rating of 4 means fully plausible.

Any domain rated 1 or 2 must include a written explanation that identifies the specific clinical concern.

Reviewers also answer the overall question: could this reasonably represent a patient encountered in the stated inpatient clinical setting? The allowed answers are Yes or No.

### Result

C1 passes when all clinically relevant domains are rated 3 or 4 and the overall clinical plausibility answer is Yes.

If any domain is rated 1 or 2, or if the overall answer is No, record that revision is needed for clinical plausibility.

On the Stage 1 form, record only:

- Clinically plausible
- Revision needed for clinical plausibility

Do not record Accept, Revise, or Exclude until Stage 2 is complete.

### Technical interpretation

C1 is a clinical-realism judgment on the resident-visible export. It does not inspect the concealed family or category fields. Software already checked schema, terminology identifiers, and implemented rules. C1 asks whether a physician still finds the chart coherent.

## C2 — Intended assessment problem

### Clinical question

Does the case actually contain the medication-reconciliation or transition-of-care problem it was designed to assess?

### Reviewer should look for

Determine whether the intended problem is present, whether it matches the intended category, and whether the investigator description accurately reflects the clinical case.

### Result

Record Pass or Fail. C2 is a hard requirement. If C2 fails, the case cannot be used against its intended answer key until the problem is corrected or the case is excluded. A written explanation is required for a failure.

### Technical interpretation

This criterion checks fidelity of the deterministic injection to the planned standardized category. The planned category, the injected kind, and the answer-key category must describe the same visible target.

## C3 — Detectability

### Clinical question

Could an internal medicine resident identify and resolve the intended problem using only the clinical information provided in the case?

### Reviewer should look for

Consider whether all necessary evidence is available, whether important information is missing, whether the case is ambiguous, and whether wording or formatting gives away the answer. For Family 2, the trigger or precondition must be visible and unambiguous.

### Result

Record Pass or Fail. C3 is a hard requirement. A written explanation is required for a failure.

### Technical interpretation

This corresponds to evidentiary sufficiency and cue integrity in the CliniProof assessment model. The resident export must be sufficient without investigator fields.

## C4 — Absence of unintended problems

### Clinical question

Apart from the intended assessment problem, does the case contain another clinically meaningful medication-reconciliation or transition-of-care problem?

### Reviewer should look for

Reviewers must actively search for additional problems. This is not simply a record of problems that happen to be noticed. After reviewing the complete case, ask whether another clinically meaningful discrepancy is present that a reasonable resident could interpret as an assessment target.

### Result

Record Pass or Fail. C4 is a hard requirement. If the result is Fail, identify the additional problem, the medication or clinical issue involved, and why it is clinically meaningful.

### Technical interpretation

Error isolation means exactly one intended assessment target on error-bearing cases and zero on clean controls. An unintended second target makes the answer key unusable.

## C5 — Expected learner difficulty

### Clinical question

How difficult would this case likely be for an internal medicine resident?

### Reviewer should look for

Provide a provisional expert estimate using Easy, Moderate, Hard, or Inappropriate / outlier.

This is an expert estimate of difficulty. Actual difficulty should ultimately be determined from resident performance.

### Result

C5 is advisory. It should not by itself cause a case to fail validation.

### Technical interpretation

Any prior difficulty field in the answer key is optional metadata, not a software-computed score.

## Family-specific guidance for C2 through C4

Criteria C2 through C4 must account for different clinical structures. Family 1 problems generally involve comparing home, inpatient, and discharge medication lists. Family 2 problems may leave those lists unchanged and instead omit a required transition action.

### Family 1 — medication-list and transition discrepancies

#### Medication omitted at discharge (`f1_omission`)

A medication intended to continue after hospitalization is absent from the discharge medication list without a documented reason.

#### Medication inappropriately added or continued (`f1_commission`)

A medication that should not be on the discharge list, for example one that was held or stopped, appears there without a documented decision to continue it.

#### Unexplained dose discrepancy (`f1_dose_mismatch`)

The discharge dose differs from the intended continued dose without an explanation.

#### Unexplained route discrepancy (`f1_route_mismatch`)

The discharge route differs from the intended continued route without an explanation.

#### Unexplained frequency discrepancy (`f1_frequency_mismatch`)

The discharge frequency differs from the intended continued frequency without an explanation.

#### Unexplained therapeutic substitution (`f1_therapeutic_substitution`)

The discharge list replaces an intended continued medication with another agent of the same class without documenting an intentional switch.

### Family 2 — transition-of-care gaps

These problems may involve absence of monitoring, follow-up, supply, restart planning, or another transition action. Do not identify Family 2 solely by comparing medication lists. For Family 2, the trigger or precondition must be visible, and the missing companion action is the specified target.

#### Required outpatient monitoring not arranged (`f2_monitoring_not_arranged`)

Warfarin is continued at discharge, but outpatient INR monitoring has not been arranged. In CliniProof this is classified as a Family 2 transition-of-care gap because the medication order itself remains unchanged; the missing element is the required follow-up action.

#### Held medication without a restart plan (`f2_held_med_no_restart_plan`)

A home medication is intentionally held in the hospital for a legitimate temporary reason, but discharge documentation does not say when or under what conditions it should be resumed.

#### Insufficient medication supply (`f2_insufficient_supply`)

Days’ supply at discharge is too short to last until the planned follow-up. The medication identity on the list may be correct; the missing element is enough supply to bridge to the next visit.

#### Hospital-only medication continued after discharge (`f2_hospital_only_continued`)

A medication started for an inpatient-only indication is still on the discharge list. Reviewers should notice that a hospital-only product was not stopped at the transition home.

#### Temporary inpatient substitution not addressed at discharge (`f2_inpatient_substitution_not_reverted`)

A temporary inpatient substitute was used, but discharge does not revert to home therapy or document an intentional decision to continue the substitute.

#### Follow-up missing for an unresolved treatment decision (`f2_pending_decision_followup_missing`)

A treatment decision was left pending, but no follow-up is arranged to resolve it. The medication list may look intact, but the chart does not say when or by whom the unresolved decision will be revisited.

#### Required companion medication omitted (`f2_coprescription_omitted`)

The taxonomy also defines this category for a situation in which a clinically required companion medication is missing. This category is not included in the current validation set because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing or encoding an unsupported rule, the system currently rejects this category.

## Reviewer recommendation

Each reviewer records one independent recommendation after completing C1 through C5. Consensus is not a recommendation option on this form.

☐ Accept

☐ Revise

☐ Exclude

Accept means the case is suitable for use without clinically meaningful revision. Revise means the case requires one or more changes before it should be used. Exclude means the case should not be used in the validation set because its problems cannot be reasonably corrected without substantially reconstructing it.

If revision is requested:

### Recommended revision

____________________________________

### Clinical reason for revision

____________________________________

Recommended revisions are required whenever Revise is selected. Examples may include changing an implausible formulation, clarifying the hospital course, correcting an unrealistic laboratory unit, adding information needed to detect the intended problem, or removing an unintended second discrepancy.

Do not automatically modify a case based on reviewer comments. Human review comments are recommendations that must be considered by the study team. Do not overwrite the frozen CLINIPROOF_TAXONOMY_V1 case files during human review. Reviewer comments and revision requests should be stored separately.

## Consensus review

Complete only when independent reviewers disagree.

Reviewer A initial recommendation:

Reviewer B initial recommendation:

Areas of disagreement:

Consensus discussion summary:

Consensus outcome:

☐ Accepted

☐ Revision required

☐ Excluded

☐ Unresolved

Preserve both original independent ratings. Show both reviewers the areas of disagreement. Discuss the clinical rationale. Record a consensus outcome separately. Do not overwrite original reviewer ratings with the consensus result.

If the two reviewers cannot reach consensus, mark Unresolved. Do not automatically accept the case. An unresolved case is not considered clinically validated. It may receive an additional clinical opinion if one becomes available, or it may remain excluded from the clinically validated set.

Structured consensus review is required when reviewers disagree on C1 pass versus revision needed, when either reviewer fails C2, when reviewers disagree on C2, C3, C4, or Accept / Revise / Exclude, or when clinically important reviewer comments conflict. Cases with agreement require no consensus discussion unless the investigators choose to review them.

If the consensus outcome is Revision required, record the specific requested revision, the reason, the criterion affected, and the date or version of the revision. After the case is revised, it should be reviewed again. Only the criteria affected by the revision need to be repeated unless the change materially alters the whole case. If a revision changes the clinical presentation, medication regimen, target discrepancy, evidence needed to detect the problem, or answer key, then repeat the relevant C1 through C4 assessments.
"""

REVIEWER_PROTOCOL_MD = """# Clinical Validation Protocol

This protocol describes independent dual expert review with structured consensus resolution for the frozen CliniProof validation set whose batch code is `CLINIPROOF_TAXONOMY_V1`. The set contains twenty-four synthetic inpatient cases labeled VAL-201 through VAL-224. The method is not a Delphi process and is not a modified Delphi process.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

### Reviewers

Two clinical experts independently review all 24 cases. There is no third reviewer in the primary protocol. Each reviewer records original ratings before any discussion occurs. Those original ratings must be preserved.

### Round 1: blinded plausibility assessment

Both reviewers review the resident-facing cases and complete C1 before seeing the answer key. They use [`plausibility_only_packet.md`](plausibility_only_packet.md). They do not see whether a case is a control, the intended error family, the intended error category, the medication targeted by the assessment, the correct action, or any other answer-key field.

They score eight domains on a 1-to-4 scale and answer whether the chart could reasonably represent a patient encountered in the stated inpatient clinical setting. C1 ratings are submitted and locked before Round 2 begins. The Stage 1 result is Clinically plausible or Revision needed for clinical plausibility. Accept, Revise, and Exclude are not recorded at this stage.

### Round 2: assessment validation

After C1 ratings are locked, both reviewers receive the investigator target in [`clinician_validation_packet.md`](clinician_validation_packet.md) and independently complete C2 through C5 and their overall recommendation. C2 asks whether the intended assessment problem is present and correctly described. C3 asks whether an internal medicine resident could detect and resolve that problem from the case documents alone. C4 requires an active search for another clinically meaningful medication-reconciliation or transition-of-care problem. C5 is an expert estimate of expected learner difficulty and is advisory.

The independent recommendation is Accept, Revise, or Exclude. If Revise is selected, recommended revisions are required. Reviewer comments are recommendations for the study team. They do not automatically change frozen case files.

### Consensus

Disagreements on clinically meaningful criteria or final recommendation are discussed after independent review. Original ratings remain unchanged. A separate consensus outcome is recorded on [`consensus_worksheet.csv`](consensus_worksheet.csv), not on the independent reviewer row.

Structured consensus review is used when reviewers disagree on C1 pass versus revision needed, when either reviewer fails C2, when reviewers disagree on C2, C3, C4, or Accept / Revise / Exclude, or when clinically important reviewer comments conflict. Cases with agreement require no consensus discussion unless the investigators choose to review them.

During consensus review, both original independent ratings are preserved, both reviewers are shown the areas of disagreement, the clinical rationale is discussed, and a consensus outcome is recorded separately as Accepted, Revision required, Excluded, or Unresolved. Consensus is not itself a case disposition on the independent form.

### Revisions

Reviewers may request specific changes. Cases requiring revision are corrected only after the initial ratings have been recorded. Revised cases are then reviewed again as appropriate. Only the criteria affected by the revision need to be repeated unless the change materially alters the whole case. If a revision changes the clinical presentation, the medication regimen, the target discrepancy, the evidence needed to detect the problem, or the answer key, then the relevant C1 through C4 assessments are repeated.

Do not silently modify the frozen CLINIPROOF_TAXONOMY_V1 case files. For the current validation study, the existing frozen cases remain the original validation candidates. Reviewer comments and revision requests should be stored separately from those frozen source files.

### Unresolved cases

If consensus cannot be achieved, the case is not considered clinically validated. It may receive another expert opinion if available or be excluded. An unresolved case must not be treated as accepted.

## Agreement reporting

Planned agreement reporting uses raw agreement for C2 through C4, raw agreement for the overall recommendation, and weighted Cohen's kappa for ordinal C1 ratings where appropriate. Weighted Cohen's kappa may optionally be reported for C5.

Because the validation set contains only 24 cases, agreement coefficients will be interpreted alongside the underlying counts and percentage agreement rather than as standalone evidence of reliability.

Do not overclaim statistical reliability. Kappa is not a criterion for whether a case passes validation. Case-level decisions remain the independent ratings, the separate consensus outcome when discussion occurs, and the study team's subsequent handling of requested revisions.

Independent ratings are recorded on [`clinical_validation_worksheet.csv`](clinical_validation_worksheet.csv). Consensus outcomes are recorded on [`consensus_worksheet.csv`](consensus_worksheet.csv). Criterion definitions are in [`validation_rubric.md`](validation_rubric.md).
"""

CLINICAL_VALIDATION_WORKSHEET_CSV = (
    'validation_case_id,reviewer_id,review_round,c1_presentation_demographics,c1_diagnosis_presentation_fit,c1_vital_signs,c1_laboratory_findings,c1_medication_regimen,c1_hospital_course,c1_cross_document_consistency,c1_discharge_followup,c1_global_plausibility,c1_comments,c2_intended_problem_present,c2_comments,c3_detectable_from_case,c3_comments,c4_no_unintended_problem,c4_additional_problem,c4_comments,c5_expected_difficulty,c5_comments,initial_recommendation,recommended_revisions,overall_comments\n'
)

CONSENSUS_WORKSHEET_CSV = (
    'validation_case_id,reviewer_a_recommendation,reviewer_b_recommendation,criteria_in_disagreement,consensus_discussion_summary,consensus_outcome,revision_required,revision_description,re_review_required,notes\n'
)

HOW_CLINIPROOF_WORKS_MD = """# How CliniProof Builds and Validates a Case

This overview is for residents who are curious about the technology, physicians, medical educators, pharmacists, informatics staff, and AI engineers. It explains the system in clinical language first, then names the software pieces.

It discusses how cases are made. It does not reveal which frozen case labeled VAL-201 through VAL-224 contains which assessment target.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

## A. Clinical overview

CliniProof creates synthetic inpatient medication-reconciliation cases with a known assessment target.

Medication reconciliation is the clinical work of making a best-possible medication history, comparing it with inpatient orders and the discharge list, and ensuring that holds, stops, continuations, substitutions, supplies, monitoring, and follow-up are explicit and safe.

Some cases are clean controls. In those charts the software leaves the encounter without an intentionally planted assessment problem, so reviewers and residents can also see an intact reconciliation. Other cases receive exactly one planned problem after the clean chart has already passed automated checks. Four of the twenty-four frozen cases are clean controls. They are included so that residents cannot assume that every case necessarily contains an error. This document does not say which identifiers are controls.

Family 1 problems, recorded in software as `family_1`, are discrepancies on the medication lists themselves: a drug missing at discharge, an extra drug, or an unexplained change in dose, route, frequency, or product.

Family 2 problems, recorded as `family_2`, are transition-of-care gaps. The discharge medication identity may be unchanged; what is missing is a required companion action such as INR monitoring, a restart plan for a held drug, enough days’ supply, stopping a hospital-only drug, reverting a temporary substitute, or arranging follow-up for an unresolved decision.

Do not identify Family 2 solely by comparing home versus discharge lists.

### Implemented categories

Each category has a clinical name and a standardized identifier used in software and investigator materials. The current dataset uses the canonical CliniProof taxonomy. The identifier is shown in parentheses after the clinical name.

#### Family 1

##### Medication omitted at discharge (`f1_omission`)

A medication intended to continue after hospitalization is absent from the discharge medication list without a documented reason. This is a Family 1 medication-transition discrepancy. The clean expected discharge medication is present before assessment modification and removed from the final discharge list.

##### Medication inappropriately added or continued (`f1_commission`)

A medication that should not continue, for example one held or stopped, appears on the discharge list. The injector adds or retains a discharge-list entry that the clean case had omitted for a documented reason.

##### Unexplained dose discrepancy (`f1_dose_mismatch`)

The discharge dose differs from the intended continued dose without a documented explanation. This is a Family 1 medication-list discrepancy. After the clean case passes validation, the injector changes only the dose field on the discharge entry. Home and inpatient lists remain unchanged so that a reviewer can see the intended dose.

##### Unexplained route discrepancy (`f1_route_mismatch`)

The discharge route differs from the intended continued route without a documented explanation. For example, an oral medication might appear as a different route at discharge with no rationale in the chart.

##### Unexplained frequency discrepancy (`f1_frequency_mismatch`)

The discharge frequency differs from the intended continued frequency without a documented explanation. For example, a once-daily medication might appear as twice daily at discharge, or the reverse.

##### Unexplained therapeutic substitution (`f1_therapeutic_substitution`)

The discharge list shows a same-class substitute instead of the intended continued product, without documenting an intentional switch. The original product remains visible on the home or inpatient list so that the substitution can be noticed.

#### Family 2

##### Required outpatient monitoring not arranged (`f2_monitoring_not_arranged`)

Warfarin is continued at discharge, but outpatient INR monitoring has not been arranged. In CliniProof this is classified as a Family 2 transition-of-care gap because the medication order itself remains unchanged; the missing element is the required follow-up action. After the clean case passes validation, the injector removes the expected monitoring record. The medication itself remains unchanged.

##### Held medication without a restart plan (`f2_held_med_no_restart_plan`)

The original medication is intentionally stopped during hospitalization for a legitimate temporary reason, but the discharge documentation does not tell the patient or outpatient clinician when or under what conditions it should be resumed. The hold itself remains visible; what is missing is the restart plan.

##### Insufficient medication supply (`f2_insufficient_supply`)

Days’ supply at discharge is shortened so that treatment cannot last until the planned follow-up. The medication identity on the discharge list may be correct; the missing element is enough supply to bridge to the next visit.

##### Hospital-only medication continued after discharge (`f2_hospital_only_continued`)

A drug started for an inpatient-only indication remains on the discharge list. Reviewers are expected to notice that a hospital-only product was not stopped at the transition home.

##### Temporary inpatient substitution not addressed at discharge (`f2_inpatient_substitution_not_reverted`)

A temporary inpatient substitute is left in place without reverting to home therapy or documenting an intentional decision to continue the substitute.

##### Follow-up missing for an unresolved treatment decision (`f2_pending_decision_followup_missing`)

A pending therapeutic decision has no arranged follow-up. The medication list may look intact, but the chart does not say when or by whom the unresolved decision will be revisited.

##### Required companion medication omitted (`f2_coprescription_omitted`)

The taxonomy also defines this category for a situation in which a clinically required companion medication is missing. This category is not included in the current validation set because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing or encoding an unsupported rule, the system currently rejects this category.

## B. Source-backed versus synthetic information

A source-backed concept is not the same thing as real patient data. An RxNorm identifier for warfarin means the concept came from RxNorm, not that a real patient was taking warfarin.

The table below separates the kinds of information that appear on a case. Official vocabulary rows are retrieved from terminology services. Patient-specific numbers and stories are generated. Assessment discrepancies are introduced only after the clean chart has passed automated checks.

| Type of information | Example | How it is obtained |
| --- | --- | --- |
| Medication concept | Warfarin | Retrieved from RxNorm |
| Diagnosis concept | Heart failure | Retrieved from ICD-10-CM |
| Laboratory test | Creatinine | Retrieved from LOINC |
| Unit | mmol/L | Retrieved from UCUM or LOINC |
| Age | 72 | Synthetically generated |
| Blood pressure | 128/74 | Synthetically generated |
| Lab result | Creatinine 1.3 | Synthetic patient value |
| Clinical narrative | History of present illness | Template sentences, or optional LLM wording of already selected facts |
| Assessment discrepancy | Missing monitoring | Introduced deterministically after clean validation |

Official source ranking can yield technically valid but clinically atypical formulations or units, for example a solution or gel, or an SI laboratory unit. Those oddities are left visible for clinician review. They are not silently rewritten.

## C. Generation pipeline

Cases are built in a fixed order. Each stage completes before the next stage begins.

1. A clinical scenario is selected. A clinical scenario is an inpatient teaching skeleton chosen by an operator. It specifies specialty, age band, diagnosis and medication search phrases, and which assessment categories are allowed.
2. Terminology is resolved. Search phrases are matched to identifiers already stored from official services, including RxNorm, ICD-10-CM, LOINC, UCUM, and related sources. The generator does not invent codes.
3. A clean synthetic patient is assembled: demographics, vital signs, laboratory values, medication lists, notes, and follow-up, internally consistent with the scenario and the stored concepts.
4. Rule checks apply a small set of source-backed if-then constraints, and only those with attached DailyMed or RxClass evidence. This is not a complete clinical guideline.
5. Clean validation checks structure, confirms that every coded concept exists in local reference tables, confirms that hard rules hold, and confirms that the clean chart does not already contain the assessment target that would later be planted.
6. Assessment target eligibility asks whether the planned category can actually be applied to this case. If not, generation stops. Another category is not silently substituted.
7. Controlled error introduction applies exactly one planned change for assessment cases. Clean controls skip this step.
8. Post-error validation checks that the intended target is now present, that required evidence remains visible, and that a second assessment target was not introduced.
9. Blinded resident export gives residents the chart without family, category, trigger metadata, or answer keys.
10. Clinician validation is the human step. Two clinical reviewers independently complete blinded clinical plausibility (C1). After those ratings are submitted and locked, they independently complete C2 through C5 and an Accept, Revise, or Exclude recommendation. Important disagreements undergo structured consensus review. Original independent ratings are preserved. Automated checks cannot certify realism or educational appropriateness.

## D. What OpenAI does

OpenAI is optional in the CliniProof pipeline and is used only to help word narrative text from clinical facts that have already been selected by the structured generator. It does not choose diagnoses, medications, terminology codes, error categories, clinical rules, or answer-key content.

The current frozen validation set uses template narrative rather than OpenAI. The freeze command sets the OpenAI flag to false.

Raw patient-source rows are never sent to a language model.

## E. Why machine validation is not clinical validation

The software performs automated checks of structure, terminology provenance, implemented clinical constraints, and the intended assessment manipulation. These checks are useful for detecting technical inconsistencies, but they do not establish that a case is clinically realistic, educationally appropriate, or representative of actual practice. Those judgments require review by clinicians.

Until clinicians finish review, every generated record remains a machine-validated synthetic resident-review case pending clinician validation.

## F. Technical implementation

Physicians can stop here. The table below is for engineers and informatics staff. It names the repository files that implement each function already described in clinical language.

| Function | Implementation |
| --- | --- |
| Scenario definitions | `data/bootstrap/scenarios.json` |
| Terminology bootstrap | `app/services/bootstrap.py` |
| Case generation | `app/services/generation.py` |
| Error taxonomy | `app/services/error_taxonomy.py` |
| Error injection | `app/services/error_injection.py` |
| Validation | `app/services/validation.py` |
| Freeze/export | `app/services/validation_batch.py` |
| Optional narrative LLM | `app/openai/narrative.py` |
| Readable Markdown views | `app/services/readable_packets.py` |

Standardized families are Family 1 (`family_1`), Family 2 (`family_2`), and no planted target (`none`) for a clean control. Standardized categories are the `f1_*` and `f2_*` identifiers listed above. Unknown names fail rather than being aliased.

Readable packets are regenerated with `python scripts/build_readable_validation_packets.py` and do not rewrite frozen JSON.
"""

DEVELOPER_NOTES_MD = """# CliniProof Implementation Notes for Clinical Informatics and AI Engineering

This note assumes you understand software engineering and may not have a clinical training background. It translates the medical objective into the modules that implement it.

It explains mechanisms. It does not map any frozen identifier in the range VAL-201 through VAL-224 to a hidden assessment target. That mapping exists only in investigator-only files.

Until clinicians finish review, treat every record as a machine-validated synthetic resident-review case pending clinician validation.

## Clinical objective

Hospitals reconcile medications at admission and discharge so that intended home therapy is neither dropped nor continued unsafely, and so that required monitoring and follow-up actually occur.

CliniProof builds synthetic inpatient charts for that task. Each assessment item has a known target chosen before generation, not discovered afterwards by a model. Residents see a chart. Investigators see the target. Human clinicians still decide whether the chart is believable enough to use.

## Why canonical vocabularies are used

If the case said only “a heart-failure pill,” reviewers could not tell which product was meant, and software could not check rules. Official vocabularies give citable identifiers. RxNorm identifiers (RXCUI) name medications. ICD-10-CM codes name diagnoses. LOINC codes name laboratory tests. UCUM codes name units.

Those identifiers are stored only after an official service returns them, together with provenance fields for the source system, source version, and retrieval time. The generator never invents a code. SNOMED CT is not ingested here; SNOMED fields stay empty rather than being fabricated.

## Source-backed versus synthetic

The table below is the same distinction clinicians need, restated for engineers. A source-backed warfarin concept is not evidence that a real patient was taking warfarin.

| Layer | Meaning |
| --- | --- |
| Source-backed concept | The type of thing, such as warfarin as an RxNorm identifier or creatinine as a LOINC test, came from an official terminology |
| Synthetic value | The patient-specific number or story, such as age 72, creatinine 1.3, or the history-of-present-illness sentences, was generated |
| Deterministic assessment change | After the clean chart passed checks, software applied one planned edit |

## Scenario structure

The file `data/bootstrap/scenarios.json` holds teaching skeletons: specialty, age band, search phrases for diagnoses, symptoms, medications, and labs, and which standardized assessment categories are allowed. Matching happens against already bootstrapped reference rows in `app/services/bootstrap.py`, not against live free text.

## Clean-case concept

Generation in `app/services/generation.py` first builds a clean structured encounter: demographics, presentation, medications in three contexts (home, inpatient, and discharge), labs, vitals, notes, monitoring, follow-up, and instructions. Clean means the chart should not already contain the assessment target that the plan might later introduce.

A small rules engine in `app/services/rules.py` applies only conditionals that have attached DailyMed or RxClass evidence. There are few such rules. They are not a complete specialty guideline.

## Family 1 versus Family 2

Identifiers live in `app/services/error_taxonomy.py`.

Family 1 (`family_1`) means the discharge list is wrong relative to intended continuation. The following table lists the clinical meaning first and the software identifier second.

| Clinical meaning | Identifier |
| --- | --- |
| Medication omitted at discharge | `f1_omission` |
| Medication inappropriately added or continued | `f1_commission` |
| Unexplained dose discrepancy | `f1_dose_mismatch` |
| Unexplained route discrepancy | `f1_route_mismatch` |
| Unexplained frequency discrepancy | `f1_frequency_mismatch` |
| Unexplained therapeutic substitution | `f1_therapeutic_substitution` |

Family 2 (`family_2`) means a required transition action is missing; the continued-drug identity may be unchanged.

| Clinical meaning | Identifier |
| --- | --- |
| Required outpatient monitoring not arranged | `f2_monitoring_not_arranged` |
| Held medication without a restart plan | `f2_held_med_no_restart_plan` |
| Insufficient medication supply | `f2_insufficient_supply` |
| Hospital-only medication continued after discharge | `f2_hospital_only_continued` |
| Temporary inpatient substitution not addressed at discharge | `f2_inpatient_substitution_not_reverted` |
| Follow-up missing for an unresolved treatment decision | `f2_pending_decision_followup_missing` |
| Required companion medication omitted | `f2_coprescription_omitted` |

Held medication without a restart plan means the original medication is intentionally stopped during hospitalization for a legitimate temporary reason, but the discharge documentation does not tell the patient or outpatient clinician when or under what conditions it should be resumed. That maps to `f2_held_med_no_restart_plan`.

Required outpatient monitoring not arranged means, for example, warfarin continues at discharge but outpatient INR monitoring was not scheduled. That maps to `f2_monitoring_not_arranged`. The medication row stays; the monitoring record is what changes.

The taxonomy also defines required companion medication omitted (`f2_coprescription_omitted`). This category is not included in the current validation set because the software does not yet have a sufficiently source-backed deterministic rule for deciding when such a companion medication is required (`not_yet_implementable`). Rather than guessing, freeze currently rejects this category.

Do not implement Family 2 detection as a simple difference of the three medication lists.

## Eligibility, injection, and no fallback

The freeze plan names the error family and error category before generation, in `data/validation/batch_plan.json`.

The taxonomy module in `app/services/error_taxonomy.py` decides whether the clean case is eligible for that category. For example, there must be a continued discharge drug to omit, or a monitoring-dependency rule must match.

The injector in `app/services/error_injection.py` then applies the exact edit, or skips injection for a clean control whose category is `none`.

If the category is unknown, ineligible, or marked `not_yet_implementable`, freeze aborts. It does not pick a different error. A language model never chooses the category.

## Clean state and injected state

The investigator answer key stores both states. The clean expected state is what the field was after clean validation, for example the omitted drug present on the discharge list. The injected state is what residents see after the edit, for example absent.

Residents must not receive these fields. The readable investigator packet is the human view of the same concealed specification.

## Machine validation

Validation in `app/services/validation.py` and freeze-time checks in `app/services/validation_batch.py` cover structure, terminology integrity, implemented rules, category eligibility, the expected state transition, answer-key consistency, isolation of a second target, and leak checks on the resident export.

The software performs automated checks of structure, terminology provenance, implemented clinical constraints, and the intended assessment manipulation. These checks are useful for detecting technical inconsistencies, but they do not establish that a case is clinically realistic, educationally appropriate, or representative of actual practice. Those judgments require review by clinicians.

## Resident blinding

The resident JSON omits answer-key objects, internal generation identifiers, family and category fields, trigger metadata, and clean or injected state. Readable files `all_cases.md`, `plausibility_only_packet.md`, and the individual case pages are derived only from that blinded export.

## Clinician dual expert review

Human validation of the frozen set uses independent dual expert review with structured consensus resolution. Two clinical reviewers complete blinded C1, then independently complete C2 through C5. Original independent ratings are stored on `clinical_validation_worksheet.csv`. Consensus outcomes are stored separately on `consensus_worksheet.csv` and do not overwrite those ratings. Reviewer comments do not rewrite frozen JSON. The protocol is `reviewer_protocol.md`.

## Freeze immutability and provenance

Frozen files for batch `CLINIPROOF_TAXONOMY_V1` under `data/validation/` are the study source of truth. Regenerating live terminology from APIs is not expected to reproduce bit-identical JSON. Readable Markdown is allowed to be regenerated from those frozen files; the frozen files themselves must not be rewritten to improve clinical content.

Each frozen assignment records scenario, seed, family, category, source-version snapshots, and validation statuses in the investigator key and manifest.

## Optional narrative language model

The module `app/openai/narrative.py` may reword admission prose from already chosen names. It is not a case generator. OpenAI is optional in the CliniProof pipeline and is used only to help word narrative text from clinical facts that have already been selected by the structured generator. It does not choose diagnoses, medications, terminology codes, error categories, clinical rules, or answer-key content. The committed freeze used templates only.

## Reproducing the pipeline

Operators who already have a database and terminology bootstrap can run the following commands. Do not re-freeze expecting to replace VAL-201 through VAL-224. To refresh clinician-facing Markdown only, run the readable-packet script.

```bash
clinical-case-generator db-init
clinical-case-generator bootstrap-reference-data
clinical-case-generator freeze-validation-batch
clinical-case-generator export-validation-batch
python scripts/build_readable_validation_packets.py
```
"""
