"""phase 1 clinical schema

Revision ID: 1c236aeaadc7
Revises:
Create Date: 2026-09-21 20:17:02.615291

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.models.reference import DataSourceRegistry
from app.repositories.reference import SOURCE_REGISTRY_ROWS
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c236aeaadc7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_cases',
    sa.Column('case_id_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('case_status', sa.String(length=64), nullable=True),
    sa.Column('clean_case', sa.Boolean(), nullable=True),
    sa.Column('generation_source', sa.String(length=64), nullable=True),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('admission_dx', sa.Text(), nullable=True),
    sa.Column('disposition_status', sa.String(length=64), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('patient_name', sa.String(length=256), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=64), nullable=True),
    sa.Column('ethnicity', sa.String(length=128), nullable=True),
    sa.Column('specialty', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("btrim(case_id_code) <> ''", name=op.f('ck_clinical_cases_case_id_code_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_cases')),
    sa.UniqueConstraint('case_id_code', name=op.f('uq_clinical_cases_case_id_code'))
    )
    op.create_table('data_source_registry',
    sa.Column('source_code', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=256), nullable=True),
    sa.Column('source_category', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('access_type', sa.String(length=64), nullable=True),
    sa.Column('requires_credentials', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('license_or_terms', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=32), server_default=sa.text("'never_synced'"), nullable=False),
    sa.Column('records_imported', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("btrim(source_code) <> ''", name=op.f('ck_data_source_registry_source_code_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source_registry')),
    sa.UniqueConstraint('source_code', name=op.f('uq_data_source_registry_source_code'))
    )
    op.create_table('ref_clinical_distributions',
    sa.Column('source_dataset', sa.String(length=64), nullable=True),
    sa.Column('source_dataset_version', sa.String(length=64), nullable=True),
    sa.Column('clinical_context', sa.String(length=128), nullable=True),
    sa.Column('diagnosis_code', sa.String(length=32), nullable=True),
    sa.Column('diagnosis_system', sa.String(length=32), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('care_setting', sa.String(length=64), nullable=True),
    sa.Column('variable_type', sa.String(length=64), nullable=True),
    sa.Column('variable_code', sa.String(length=64), nullable=True),
    sa.Column('variable_name', sa.String(length=256), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('mean', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('median', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p05', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p10', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p25', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p75', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p90', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p95', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('min_observed', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_observed', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('calculation_method', sa.String(length=128), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("source_dataset IS NULL OR source_dataset <> 'MIMIC_IV_RAW'", name=op.f('ck_ref_clinical_distributions_no_raw_mimic_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_clinical_distributions'))
    )
    op.create_index('uq_ref_clinical_distributions_aggregate', 'ref_clinical_distributions', ['source_dataset', 'clinical_context', 'variable_code', 'age_min', 'age_max', 'sex', 'care_setting', 'timepoint'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('ref_devices',
    sa.Column('device_identifier', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=512), nullable=True),
    sa.Column('brand_name', sa.String(length=256), nullable=True),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('device_description', sa.Text(), nullable=True),
    sa.Column('device_category', sa.String(length=128), nullable=True),
    sa.Column('device_term', sa.String(length=256), nullable=True),
    sa.Column('implantable', sa.Boolean(), nullable=True),
    sa.Column('single_use', sa.Boolean(), nullable=True),
    sa.Column('sterile', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_devices'))
    )
    op.create_index(op.f('ix_ref_devices_device_identifier'), 'ref_devices', ['device_identifier'], unique=False)
    op.create_table('ref_diagnoses',
    sa.Column('snomed_code', sa.String(length=32), nullable=True),
    sa.Column('icd10cm_code', sa.String(length=16), nullable=True),
    sa.Column('preferred_name', sa.String(length=512), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_category', sa.String(length=128), nullable=True),
    sa.Column('parent_concept_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(snomed_code IS NOT NULL AND btrim(snomed_code) <> '') OR (icd10cm_code IS NOT NULL AND btrim(icd10cm_code) <> '')", name=op.f('ck_ref_diagnoses_has_snomed_or_icd10')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_diagnoses'))
    )
    op.create_index('ix_ref_diagnoses_icd10cm_code', 'ref_diagnoses', ['icd10cm_code'], unique=False)
    op.create_index('ix_ref_diagnoses_snomed_code', 'ref_diagnoses', ['snomed_code'], unique=False)
    op.create_table('ref_drug_labels',
    sa.Column('set_id', sa.String(length=64), nullable=True),
    sa.Column('rxcui', sa.String(length=64), nullable=True),
    sa.Column('drug_name', sa.String(length=512), nullable=True),
    sa.Column('active_ingredient', sa.Text(), nullable=True),
    sa.Column('indication_text', sa.Text(), nullable=True),
    sa.Column('dosage_text', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=128), nullable=True),
    sa.Column('contraindications_text', sa.Text(), nullable=True),
    sa.Column('warnings_text', sa.Text(), nullable=True),
    sa.Column('renal_impairment_text', sa.Text(), nullable=True),
    sa.Column('hepatic_impairment_text', sa.Text(), nullable=True),
    sa.Column('geriatric_use_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_drug_labels'))
    )
    op.create_index('ix_ref_drug_labels_drug_name', 'ref_drug_labels', ['drug_name'], unique=False)
    op.create_index('ix_ref_drug_labels_rxcui', 'ref_drug_labels', ['rxcui'], unique=False)
    op.create_index('ix_ref_drug_labels_set_id', 'ref_drug_labels', ['set_id'], unique=False)
    op.create_table('ref_lab_tests',
    sa.Column('loinc_code', sa.String(length=64), nullable=False),
    sa.Column('long_common_name', sa.String(length=512), nullable=True),
    sa.Column('short_name', sa.String(length=256), nullable=True),
    sa.Column('component', sa.String(length=256), nullable=True),
    sa.Column('property', sa.String(length=64), nullable=True),
    sa.Column('time_aspect', sa.String(length=64), nullable=True),
    sa.Column('system_specimen', sa.String(length=128), nullable=True),
    sa.Column('scale', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.Column('class_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('example_ucum_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(loinc_code) <> ''", name=op.f('ck_ref_lab_tests_loinc_code_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_lab_tests')),
    sa.UniqueConstraint('loinc_code', name=op.f('uq_ref_lab_tests_loinc_code'))
    )
    op.create_table('ref_medications',
    sa.Column('rxcui', sa.String(length=64), nullable=False),
    sa.Column('concept_name', sa.String(length=512), nullable=True),
    sa.Column('generic_name', sa.String(length=512), nullable=True),
    sa.Column('brand_name', sa.String(length=512), nullable=True),
    sa.Column('ingredient', sa.String(length=512), nullable=True),
    sa.Column('strength', sa.String(length=128), nullable=True),
    sa.Column('strength_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('strength_unit', sa.String(length=64), nullable=True),
    sa.Column('dose_form', sa.String(length=128), nullable=True),
    sa.Column('route', sa.String(length=128), nullable=True),
    sa.Column('term_type', sa.String(length=32), nullable=True),
    sa.Column('is_brand', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('prescribable', sa.Boolean(), nullable=True),
    sa.Column('source_concept_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(rxcui) <> ''", name=op.f('ck_ref_medications_rxcui_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_medications')),
    sa.UniqueConstraint('rxcui', name=op.f('uq_ref_medications_rxcui'))
    )
    op.create_index('ix_ref_medications_concept_name', 'ref_medications', ['concept_name'], unique=False)
    op.create_index('ix_ref_medications_generic_name', 'ref_medications', ['generic_name'], unique=False)
    op.create_index('ix_ref_medications_ingredient', 'ref_medications', ['ingredient'], unique=False)
    op.create_table('ref_microbiology',
    sa.Column('test_loinc_code', sa.String(length=64), nullable=True),
    sa.Column('test_name', sa.String(length=512), nullable=True),
    sa.Column('specimen', sa.String(length=128), nullable=True),
    sa.Column('organism_code', sa.String(length=64), nullable=True),
    sa.Column('organism_name', sa.String(length=512), nullable=True),
    sa.Column('result_type', sa.String(length=64), nullable=True),
    sa.Column('unit_if_applicable', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_microbiology'))
    )
    op.create_index(op.f('ix_ref_microbiology_organism_code'), 'ref_microbiology', ['organism_code'], unique=False)
    op.create_index(op.f('ix_ref_microbiology_test_loinc_code'), 'ref_microbiology', ['test_loinc_code'], unique=False)
    op.create_table('ref_procedures',
    sa.Column('procedure_code', sa.String(length=64), nullable=True),
    sa.Column('code_system', sa.String(length=64), nullable=True),
    sa.Column('procedure_name', sa.String(length=512), nullable=True),
    sa.Column('procedure_category', sa.String(length=128), nullable=True),
    sa.Column('body_site', sa.String(length=128), nullable=True),
    sa.Column('laterality_applicable', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_procedures'))
    )
    op.create_index(op.f('ix_ref_procedures_code_system'), 'ref_procedures', ['code_system'], unique=False)
    op.create_index(op.f('ix_ref_procedures_procedure_code'), 'ref_procedures', ['procedure_code'], unique=False)
    op.create_table('ref_symptoms',
    sa.Column('snomed_code', sa.String(length=32), nullable=True),
    sa.Column('preferred_name', sa.String(length=512), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_system', sa.String(length=128), nullable=True),
    sa.Column('semantic_category', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_symptoms'))
    )
    op.create_index(op.f('ix_ref_symptoms_snomed_code'), 'ref_symptoms', ['snomed_code'], unique=False)
    op.create_table('ref_units',
    sa.Column('ucum_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('quantity_type', sa.String(length=128), nullable=True),
    sa.Column('canonical_unit', sa.String(length=64), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(ucum_code) <> ''", name=op.f('ck_ref_units_ucum_code_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_units')),
    sa.UniqueConstraint('ucum_code', name=op.f('uq_ref_units_ucum_code'))
    )
    op.create_table('ref_vitals',
    sa.Column('loinc_code', sa.String(length=64), nullable=True),
    sa.Column('vital_name', sa.String(length=256), nullable=True),
    sa.Column('component', sa.String(length=256), nullable=True),
    sa.Column('measurement_site', sa.String(length=128), nullable=True),
    sa.Column('preferred_ucum_unit', sa.String(length=64), nullable=True),
    sa.Column('alternative_ucum_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ref_vitals'))
    )
    op.create_index(op.f('ix_ref_vitals_loinc_code'), 'ref_vitals', ['loinc_code'], unique=False)
    op.create_table('case_answer_keys',
    sa.Column('answer_id', sa.String(length=64), nullable=True),
    sa.Column('error_family', sa.String(length=64), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('trigger_meds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detectability_location', sa.String(length=128), nullable=True),
    sa.Column('correct_action', sa.Text(), nullable=True),
    sa.Column('severity_ncc_merp', sa.String(length=32), nullable=True),
    sa.Column('difficulty_a_priori', sa.String(length=32), nullable=True),
    sa.Column('is_primary_error', sa.Boolean(), nullable=True),
    sa.Column('intentional_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_answer_keys_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_answer_keys')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_case_answer_keys_answer_id'))
    )
    op.create_index(op.f('ix_case_answer_keys_case_id'), 'case_answer_keys', ['case_id'], unique=False)
    op.create_table('case_blueprints',
    sa.Column('blueprint_id', sa.String(length=64), nullable=True),
    sa.Column('specialty', sa.String(length=128), nullable=True),
    sa.Column('primary_diagnosis_ref_id', sa.Uuid(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('hospital_day', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=64), nullable=True),
    sa.Column('target_home_med_count', sa.Integer(), nullable=True),
    sa.Column('target_problem_count', sa.Integer(), nullable=True),
    sa.Column('clean_case', sa.Boolean(), nullable=True),
    sa.Column('target_error_category', sa.String(length=64), nullable=True),
    sa.Column('target_error_medication_class', sa.String(length=128), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_diagnosis_ref_id'], ['ref_diagnoses.id'], name=op.f('fk_case_blueprints_primary_diagnosis_ref_id_ref_diagnoses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_blueprints')),
    sa.UniqueConstraint('blueprint_id', name=op.f('uq_case_blueprints_blueprint_id'))
    )
    op.create_index(op.f('ix_case_blueprints_primary_diagnosis_ref_id'), 'case_blueprints', ['primary_diagnosis_ref_id'], unique=False)
    op.create_table('case_consults',
    sa.Column('consult_id', sa.String(length=64), nullable=True),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_consults_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_consults')),
    sa.UniqueConstraint('consult_id', name=op.f('uq_case_consults_consult_id'))
    )
    op.create_index(op.f('ix_case_consults_case_id'), 'case_consults', ['case_id'], unique=False)
    op.create_table('case_devices',
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('ref_device_id', sa.Uuid(), nullable=True),
    sa.Column('device_type', sa.String(length=128), nullable=True),
    sa.Column('site', sa.String(length=128), nullable=True),
    sa.Column('placement_timepoint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('tip_location_or_confirmation', sa.Text(), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('removal_plan', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_devices_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_device_id'], ['ref_devices.id'], name=op.f('fk_case_devices_ref_device_id_ref_devices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_devices')),
    sa.UniqueConstraint('device_id', name=op.f('uq_case_devices_device_id'))
    )
    op.create_index(op.f('ix_case_devices_case_id'), 'case_devices', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_devices_ref_device_id'), 'case_devices', ['ref_device_id'], unique=False)
    op.create_table('case_diagnoses',
    sa.Column('diagnosis_id', sa.String(length=64), nullable=True),
    sa.Column('ref_diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('diagnosis_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_diagnoses_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_diagnosis_id'], ['ref_diagnoses.id'], name=op.f('fk_case_diagnoses_ref_diagnosis_id_ref_diagnoses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_diagnoses')),
    sa.UniqueConstraint('diagnosis_id', name=op.f('uq_case_diagnoses_diagnosis_id'))
    )
    op.create_index(op.f('ix_case_diagnoses_case_id'), 'case_diagnoses', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_diagnoses_ref_diagnosis_id'), 'case_diagnoses', ['ref_diagnosis_id'], unique=False)
    op.create_table('case_discharge_planning',
    sa.Column('disposition', sa.String(length=128), nullable=True),
    sa.Column('disposition_detail', sa.Text(), nullable=True),
    sa.Column('discharge_readiness', sa.String(length=64), nullable=True),
    sa.Column('anticipated_discharge_date', sa.Date(), nullable=True),
    sa.Column('transportation_needed', sa.Boolean(), nullable=True),
    sa.Column('home_health_ordered', sa.Boolean(), nullable=True),
    sa.Column('barriers_to_discharge', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dme_needed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_discharge_planning_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_discharge_planning'))
    )
    op.create_index(op.f('ix_case_discharge_planning_case_id'), 'case_discharge_planning', ['case_id'], unique=False)
    op.create_table('case_followups',
    sa.Column('followup_id', sa.String(length=64), nullable=True),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('timing', sa.String(length=128), nullable=True),
    sa.Column('with_service', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_followups_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_followups')),
    sa.UniqueConstraint('followup_id', name=op.f('uq_case_followups_followup_id'))
    )
    op.create_index(op.f('ix_case_followups_case_id'), 'case_followups', ['case_id'], unique=False)
    op.create_table('case_imaging',
    sa.Column('study_id', sa.String(length=64), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('study_type', sa.String(length=128), nullable=True),
    sa.Column('body_site', sa.String(length=128), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_imaging_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_imaging')),
    sa.UniqueConstraint('study_id', name=op.f('uq_case_imaging_study_id'))
    )
    op.create_index(op.f('ix_case_imaging_case_id'), 'case_imaging', ['case_id'], unique=False)
    op.create_table('case_instructions',
    sa.Column('instruction_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('instruction_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_instructions_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_instructions')),
    sa.UniqueConstraint('instruction_id', name=op.f('uq_case_instructions_instruction_id'))
    )
    op.create_index(op.f('ix_case_instructions_case_id'), 'case_instructions', ['case_id'], unique=False)
    op.create_table('case_intake_outputs',
    sa.Column('io_id', sa.String(length=64), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('intake_ml', sa.Integer(), nullable=True),
    sa.Column('output_ml', sa.Integer(), nullable=True),
    sa.Column('net_ml', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_intake_outputs_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_intake_outputs')),
    sa.UniqueConstraint('io_id', name=op.f('uq_case_intake_outputs_io_id'))
    )
    op.create_index(op.f('ix_case_intake_outputs_case_id'), 'case_intake_outputs', ['case_id'], unique=False)
    op.create_table('case_labs',
    sa.Column('lab_id', sa.String(length=64), nullable=True),
    sa.Column('ref_lab_id', sa.Uuid(), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('test_name', sa.String(length=256), nullable=True),
    sa.Column('value', sa.Double(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_labs_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_lab_id'], ['ref_lab_tests.id'], name=op.f('fk_case_labs_ref_lab_id_ref_lab_tests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_labs')),
    sa.UniqueConstraint('lab_id', name=op.f('uq_case_labs_lab_id'))
    )
    op.create_index(op.f('ix_case_labs_case_id'), 'case_labs', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_labs_ref_lab_id'), 'case_labs', ['ref_lab_id'], unique=False)
    op.create_table('case_medication_plans',
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('ref_medication_id', sa.Uuid(), nullable=True),
    sa.Column('drug', sa.String(length=512), nullable=True),
    sa.Column('home_state', sa.String(length=64), nullable=True),
    sa.Column('inpatient_state', sa.String(length=64), nullable=True),
    sa.Column('correct_discharge_state', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('is_error_target', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('continue', 'stop', 'restart', 'hold', 'dose_change', 'new_start')", name=op.f('ck_case_medication_plans_decision_values')),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_medication_plans_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_medication_id'], ['ref_medications.id'], name=op.f('fk_case_medication_plans_ref_medication_id_ref_medications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_medication_plans')),
    sa.UniqueConstraint('plan_id', name=op.f('uq_case_medication_plans_plan_id'))
    )
    op.create_index(op.f('ix_case_medication_plans_case_id'), 'case_medication_plans', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_medication_plans_ref_medication_id'), 'case_medication_plans', ['ref_medication_id'], unique=False)
    op.create_table('case_medication_reconciliations',
    sa.Column('medrec_id', sa.String(length=64), nullable=True),
    sa.Column('reconciliation_context', sa.String(length=32), nullable=True),
    sa.Column('medrec_status', sa.String(length=64), nullable=True),
    sa.Column('patient_able_to_participate', sa.Boolean(), nullable=True),
    sa.Column('bpmh_source', sa.String(length=128), nullable=True),
    sa.Column('bpmh_interviewer', sa.String(length=128), nullable=True),
    sa.Column('bpmh_date', sa.Date(), nullable=True),
    sa.Column('discrepancies_found', sa.Boolean(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('discrepancy_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pharmacist_review', sa.Boolean(), nullable=True),
    sa.Column('high_alert_meds_identified', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("reconciliation_context IS NULL OR reconciliation_context IN ('admission', 'discharge')", name=op.f('ck_case_medication_reconciliations_reconciliation_context_values')),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_medication_reconciliations_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_medication_reconciliations')),
    sa.UniqueConstraint('medrec_id', name=op.f('uq_case_medication_reconciliations_medrec_id'))
    )
    op.create_index(op.f('ix_case_medication_reconciliations_case_id'), 'case_medication_reconciliations', ['case_id'], unique=False)
    op.create_table('case_medications',
    sa.Column('medication_id', sa.String(length=64), nullable=True),
    sa.Column('ref_medication_id', sa.Uuid(), nullable=True),
    sa.Column('context', sa.String(length=32), nullable=True),
    sa.Column('drug', sa.String(length=512), nullable=True),
    sa.Column('reported_name', sa.String(length=512), nullable=True),
    sa.Column('dose', sa.String(length=128), nullable=True),
    sa.Column('route', sa.String(length=64), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('held_reason', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=64), nullable=True),
    sa.Column('verification_source', sa.String(length=128), nullable=True),
    sa.Column('target_or_goal', sa.Text(), nullable=True),
    sa.Column('monitoring', sa.Text(), nullable=True),
    sa.Column('quantity_or_days', sa.String(length=64), nullable=True),
    sa.Column('refills', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("context IS NULL OR context IN ('home', 'inpatient', 'inpatient_history', 'discharge')", name=op.f('ck_case_medications_context_values')),
    sa.CheckConstraint("status IS NULL OR status IN ('home', 'active', 'held', 'discontinued', 'discharge')", name=op.f('ck_case_medications_status_values')),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_medications_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_medication_id'], ['ref_medications.id'], name=op.f('fk_case_medications_ref_medication_id_ref_medications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_medications')),
    sa.UniqueConstraint('medication_id', name=op.f('uq_case_medications_medication_id'))
    )
    op.create_index(op.f('ix_case_medications_case_id'), 'case_medications', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_medications_ref_medication_id'), 'case_medications', ['ref_medication_id'], unique=False)
    op.create_table('case_microbiology',
    sa.Column('micro_id', sa.String(length=64), nullable=True),
    sa.Column('ref_micro_id', sa.Uuid(), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('specimen', sa.String(length=128), nullable=True),
    sa.Column('test', sa.String(length=256), nullable=True),
    sa.Column('organism', sa.String(length=256), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_microbiology_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_micro_id'], ['ref_microbiology.id'], name=op.f('fk_case_microbiology_ref_micro_id_ref_microbiology'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_microbiology')),
    sa.UniqueConstraint('micro_id', name=op.f('uq_case_microbiology_micro_id'))
    )
    op.create_index(op.f('ix_case_microbiology_case_id'), 'case_microbiology', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_microbiology_ref_micro_id'), 'case_microbiology', ['ref_micro_id'], unique=False)
    op.create_table('case_monitoring',
    sa.Column('monitoring_id', sa.String(length=64), nullable=True),
    sa.Column('parameter', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('trigger_for_action', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('responsible_service', sa.String(length=128), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_monitoring_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_monitoring')),
    sa.UniqueConstraint('monitoring_id', name=op.f('uq_case_monitoring_monitoring_id'))
    )
    op.create_index(op.f('ix_case_monitoring_case_id'), 'case_monitoring', ['case_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('note_id', sa.String(length=64), nullable=True),
    sa.Column('note_type', sa.String(length=64), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_notes_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_notes')),
    sa.UniqueConstraint('note_id', name=op.f('uq_case_notes_note_id'))
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('case_presentations',
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('hpi', sa.Text(), nullable=True),
    sa.Column('review_of_systems', sa.Text(), nullable=True),
    sa.Column('symptom_duration', sa.String(length=128), nullable=True),
    sa.Column('symptom_course', sa.String(length=128), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_presentations_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_presentations'))
    )
    op.create_index(op.f('ix_case_presentations_case_id'), 'case_presentations', ['case_id'], unique=False)
    op.create_table('case_problem_list',
    sa.Column('problem_id', sa.String(length=64), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('problem_type', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_problem_list_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_problem_list')),
    sa.UniqueConstraint('problem_id', name=op.f('uq_case_problem_list_problem_id'))
    )
    op.create_index(op.f('ix_case_problem_list_case_id'), 'case_problem_list', ['case_id'], unique=False)
    op.create_table('case_procedures',
    sa.Column('procedure_id', sa.String(length=64), nullable=True),
    sa.Column('ref_procedure_id', sa.Uuid(), nullable=True),
    sa.Column('procedure_name', sa.String(length=512), nullable=True),
    sa.Column('procedure_type', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('performed_by', sa.String(length=128), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=64), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('laterality', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_procedures_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_procedure_id'], ['ref_procedures.id'], name=op.f('fk_case_procedures_ref_procedure_id_ref_procedures'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_procedures')),
    sa.UniqueConstraint('procedure_id', name=op.f('uq_case_procedures_procedure_id'))
    )
    op.create_index(op.f('ix_case_procedures_case_id'), 'case_procedures', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_procedures_ref_procedure_id'), 'case_procedures', ['ref_procedure_id'], unique=False)
    op.create_table('case_return_precautions',
    sa.Column('precaution_id', sa.String(length=64), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('patient_instruction', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_return_precautions_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_return_precautions')),
    sa.UniqueConstraint('precaution_id', name=op.f('uq_case_return_precautions_precaution_id'))
    )
    op.create_index(op.f('ix_case_return_precautions_case_id'), 'case_return_precautions', ['case_id'], unique=False)
    op.create_table('case_social_supports',
    sa.Column('living_situation', sa.Text(), nullable=True),
    sa.Column('caregiver_support', sa.Text(), nullable=True),
    sa.Column('health_care_proxy', sa.Text(), nullable=True),
    sa.Column('supervision_requirement', sa.Text(), nullable=True),
    sa.Column('transportation', sa.Text(), nullable=True),
    sa.Column('financial_barriers', sa.Text(), nullable=True),
    sa.Column('health_literacy', sa.Text(), nullable=True),
    sa.Column('language_preference', sa.String(length=64), nullable=True),
    sa.Column('substance_use', sa.Text(), nullable=True),
    sa.Column('advance_directive', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_social_supports_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_social_supports'))
    )
    op.create_index(op.f('ix_case_social_supports_case_id'), 'case_social_supports', ['case_id'], unique=False)
    op.create_table('case_symptoms',
    sa.Column('symptom_id', sa.String(length=64), nullable=True),
    sa.Column('ref_symptom_id', sa.Uuid(), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_symptoms_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_symptom_id'], ['ref_symptoms.id'], name=op.f('fk_case_symptoms_ref_symptom_id_ref_symptoms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_symptoms')),
    sa.UniqueConstraint('symptom_id', name=op.f('uq_case_symptoms_symptom_id'))
    )
    op.create_index(op.f('ix_case_symptoms_case_id'), 'case_symptoms', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_symptoms_ref_symptom_id'), 'case_symptoms', ['ref_symptom_id'], unique=False)
    op.create_table('case_therapy_restrictions',
    sa.Column('therapy_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('item', sa.String(length=256), nullable=True),
    sa.Column('order_detail', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('ordered_by', sa.String(length=128), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_therapy_restrictions_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_therapy_restrictions')),
    sa.UniqueConstraint('therapy_id', name=op.f('uq_case_therapy_restrictions_therapy_id'))
    )
    op.create_index(op.f('ix_case_therapy_restrictions_case_id'), 'case_therapy_restrictions', ['case_id'], unique=False)
    op.create_table('case_vitals',
    sa.Column('vital_id', sa.String(length=64), nullable=True),
    sa.Column('ref_vital_id', sa.Uuid(), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('resp_rate', sa.Integer(), nullable=True),
    sa.Column('spo2_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('oxygen_support', sa.String(length=128), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_vitals_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_vital_id'], ['ref_vitals.id'], name=op.f('fk_case_vitals_ref_vital_id_ref_vitals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_vitals')),
    sa.UniqueConstraint('vital_id', name=op.f('uq_case_vitals_vital_id'))
    )
    op.create_index(op.f('ix_case_vitals_case_id'), 'case_vitals', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_vitals_ref_vital_id'), 'case_vitals', ['ref_vital_id'], unique=False)
    op.create_table('case_weights',
    sa.Column('weight_id', sa.String(length=64), nullable=True),
    sa.Column('timepoint', sa.String(length=64), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('dry_weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_weights_case_id_clinical_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_weights')),
    sa.UniqueConstraint('weight_id', name=op.f('uq_case_weights_weight_id'))
    )
    op.create_index(op.f('ix_case_weights_case_id'), 'case_weights', ['case_id'], unique=False)
    op.create_table('case_generation_runs',
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('validation_status', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['case_blueprints.id'], name=op.f('fk_case_generation_runs_blueprint_id_case_blueprints'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], name=op.f('fk_case_generation_runs_case_id_clinical_cases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_generation_runs')),
    sa.UniqueConstraint('run_id', name=op.f('uq_case_generation_runs_run_id'))
    )
    op.create_index(op.f('ix_case_generation_runs_blueprint_id'), 'case_generation_runs', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_case_generation_runs_case_id'), 'case_generation_runs', ['case_id'], unique=False)
    op.bulk_insert(DataSourceRegistry.__table__, [dict(row) for row in SOURCE_REGISTRY_ROWS])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_generation_runs_case_id'), table_name='case_generation_runs')
    op.drop_index(op.f('ix_case_generation_runs_blueprint_id'), table_name='case_generation_runs')
    op.drop_table('case_generation_runs')
    op.drop_index(op.f('ix_case_weights_case_id'), table_name='case_weights')
    op.drop_table('case_weights')
    op.drop_index(op.f('ix_case_vitals_ref_vital_id'), table_name='case_vitals')
    op.drop_index(op.f('ix_case_vitals_case_id'), table_name='case_vitals')
    op.drop_table('case_vitals')
    op.drop_index(op.f('ix_case_therapy_restrictions_case_id'), table_name='case_therapy_restrictions')
    op.drop_table('case_therapy_restrictions')
    op.drop_index(op.f('ix_case_symptoms_ref_symptom_id'), table_name='case_symptoms')
    op.drop_index(op.f('ix_case_symptoms_case_id'), table_name='case_symptoms')
    op.drop_table('case_symptoms')
    op.drop_index(op.f('ix_case_social_supports_case_id'), table_name='case_social_supports')
    op.drop_table('case_social_supports')
    op.drop_index(op.f('ix_case_return_precautions_case_id'), table_name='case_return_precautions')
    op.drop_table('case_return_precautions')
    op.drop_index(op.f('ix_case_procedures_ref_procedure_id'), table_name='case_procedures')
    op.drop_index(op.f('ix_case_procedures_case_id'), table_name='case_procedures')
    op.drop_table('case_procedures')
    op.drop_index(op.f('ix_case_problem_list_case_id'), table_name='case_problem_list')
    op.drop_table('case_problem_list')
    op.drop_index(op.f('ix_case_presentations_case_id'), table_name='case_presentations')
    op.drop_table('case_presentations')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_case_monitoring_case_id'), table_name='case_monitoring')
    op.drop_table('case_monitoring')
    op.drop_index(op.f('ix_case_microbiology_ref_micro_id'), table_name='case_microbiology')
    op.drop_index(op.f('ix_case_microbiology_case_id'), table_name='case_microbiology')
    op.drop_table('case_microbiology')
    op.drop_index(op.f('ix_case_medications_ref_medication_id'), table_name='case_medications')
    op.drop_index(op.f('ix_case_medications_case_id'), table_name='case_medications')
    op.drop_table('case_medications')
    op.drop_index(op.f('ix_case_medication_reconciliations_case_id'), table_name='case_medication_reconciliations')
    op.drop_table('case_medication_reconciliations')
    op.drop_index(op.f('ix_case_medication_plans_ref_medication_id'), table_name='case_medication_plans')
    op.drop_index(op.f('ix_case_medication_plans_case_id'), table_name='case_medication_plans')
    op.drop_table('case_medication_plans')
    op.drop_index(op.f('ix_case_labs_ref_lab_id'), table_name='case_labs')
    op.drop_index(op.f('ix_case_labs_case_id'), table_name='case_labs')
    op.drop_table('case_labs')
    op.drop_index(op.f('ix_case_intake_outputs_case_id'), table_name='case_intake_outputs')
    op.drop_table('case_intake_outputs')
    op.drop_index(op.f('ix_case_instructions_case_id'), table_name='case_instructions')
    op.drop_table('case_instructions')
    op.drop_index(op.f('ix_case_imaging_case_id'), table_name='case_imaging')
    op.drop_table('case_imaging')
    op.drop_index(op.f('ix_case_followups_case_id'), table_name='case_followups')
    op.drop_table('case_followups')
    op.drop_index(op.f('ix_case_discharge_planning_case_id'), table_name='case_discharge_planning')
    op.drop_table('case_discharge_planning')
    op.drop_index(op.f('ix_case_diagnoses_ref_diagnosis_id'), table_name='case_diagnoses')
    op.drop_index(op.f('ix_case_diagnoses_case_id'), table_name='case_diagnoses')
    op.drop_table('case_diagnoses')
    op.drop_index(op.f('ix_case_devices_ref_device_id'), table_name='case_devices')
    op.drop_index(op.f('ix_case_devices_case_id'), table_name='case_devices')
    op.drop_table('case_devices')
    op.drop_index(op.f('ix_case_consults_case_id'), table_name='case_consults')
    op.drop_table('case_consults')
    op.drop_index(op.f('ix_case_blueprints_primary_diagnosis_ref_id'), table_name='case_blueprints')
    op.drop_table('case_blueprints')
    op.drop_index(op.f('ix_case_answer_keys_case_id'), table_name='case_answer_keys')
    op.drop_table('case_answer_keys')
    op.drop_index(op.f('ix_ref_vitals_loinc_code'), table_name='ref_vitals')
    op.drop_table('ref_vitals')
    op.drop_table('ref_units')
    op.drop_index(op.f('ix_ref_symptoms_snomed_code'), table_name='ref_symptoms')
    op.drop_table('ref_symptoms')
    op.drop_index(op.f('ix_ref_procedures_procedure_code'), table_name='ref_procedures')
    op.drop_index(op.f('ix_ref_procedures_code_system'), table_name='ref_procedures')
    op.drop_table('ref_procedures')
    op.drop_index(op.f('ix_ref_microbiology_test_loinc_code'), table_name='ref_microbiology')
    op.drop_index(op.f('ix_ref_microbiology_organism_code'), table_name='ref_microbiology')
    op.drop_table('ref_microbiology')
    op.drop_index('ix_ref_medications_ingredient', table_name='ref_medications')
    op.drop_index('ix_ref_medications_generic_name', table_name='ref_medications')
    op.drop_index('ix_ref_medications_concept_name', table_name='ref_medications')
    op.drop_table('ref_medications')
    op.drop_table('ref_lab_tests')
    op.drop_index('ix_ref_drug_labels_set_id', table_name='ref_drug_labels')
    op.drop_index('ix_ref_drug_labels_rxcui', table_name='ref_drug_labels')
    op.drop_index('ix_ref_drug_labels_drug_name', table_name='ref_drug_labels')
    op.drop_table('ref_drug_labels')
    op.drop_index('ix_ref_diagnoses_snomed_code', table_name='ref_diagnoses')
    op.drop_index('ix_ref_diagnoses_icd10cm_code', table_name='ref_diagnoses')
    op.drop_table('ref_diagnoses')
    op.drop_index(op.f('ix_ref_devices_device_identifier'), table_name='ref_devices')
    op.drop_table('ref_devices')
    op.drop_index('uq_ref_clinical_distributions_aggregate', table_name='ref_clinical_distributions', postgresql_nulls_not_distinct=True)
    op.drop_table('ref_clinical_distributions')
    op.drop_table('data_source_registry')
    op.drop_table('clinical_cases')
    # ### end Alembic commands ###
