"""DailyMed SPL lookup keyed by an already-validated RXCUI.

Official API: https://dailymed.nlm.nih.gov/dailymed/services/v2/
Label facts are copied from SPL records. They are not generated by a model.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import httpx

from app.sources.http import as_list, get_json, new_client

DAILYMED_BASE_URL = "https://dailymed.nlm.nih.gov/dailymed/services/v2"
SOURCE_CODE = "DAILYMED"


@dataclass(frozen=True)
class DailyMedLabel:
    set_id: str
    rxcui: str
    title: str | None
    indication_text: str | None
    contraindications_text: str | None
    warnings_text: str | None
    dosage_text: str | None
    active_ingredient: str | None


class DailyMedClient:
    def __init__(
        self,
        *,
        client: httpx.Client | None = None,
        transport: httpx.BaseTransport | None = None,
        base_url: str = DAILYMED_BASE_URL,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self._owns_client = client is None
        self._client = client or new_client(transport=transport)

    def close(self) -> None:
        if self._owns_client:
            self._client.close()

    def labels_for_rxcui(self, rxcui: str, *, limit: int = 3) -> list[DailyMedLabel]:
        code = rxcui.strip()
        if code == "":
            raise ValueError("RXCUI is required for DailyMed lookup")
        listing = get_json(
            self._client,
            f"{self.base_url}/spls.json",
            source_code=SOURCE_CODE,
            params={"rxcui": code, "pagesize": str(limit)},
        )
        if not isinstance(listing, dict):
            return []
        data = as_list(listing.get("data"))
        labels: list[DailyMedLabel] = []
        for row in data[:limit]:
            if not isinstance(row, dict):
                continue
            set_id = str(row.get("setid") or row.get("set_id") or "").strip()
            title = str(row.get("title") or "").strip() or None
            if set_id == "":
                continue
            detail = get_json(
                self._client,
                f"{self.base_url}/spls/{set_id}.json",
                source_code=SOURCE_CODE,
                allow_404=True,
            )
            sections = _extract_sections(detail) if isinstance(detail, dict) else {}
            labels.append(
                DailyMedLabel(
                    set_id=set_id,
                    rxcui=code,
                    title=title,
                    indication_text=sections.get("indications"),
                    contraindications_text=sections.get("contraindications"),
                    warnings_text=sections.get("warnings"),
                    dosage_text=sections.get("dosage"),
                    active_ingredient=sections.get("active_ingredient"),
                )
            )
        return labels


def _extract_sections(detail: dict[str, Any]) -> dict[str, str]:
    found: dict[str, str] = {}
    mapping = {
        "indications": ("indication", "indications and usage"),
        "contraindications": ("contraindication",),
        "warnings": ("warning", "boxed warning", "precautions"),
        "dosage": ("dosage and administration", "dosage"),
        "active_ingredient": ("active ingredient",),
    }
    blobs = _collect_text_blobs(detail)
    for target, needles in mapping.items():
        for blob_name, blob_text in blobs:
            lowered = blob_name.lower()
            if any(needle in lowered for needle in needles) and blob_text.strip():
                found[target] = blob_text.strip()
                break
    return found


def _collect_text_blobs(node: Any, name: str = "") -> list[tuple[str, str]]:
    blobs: list[tuple[str, str]] = []
    if isinstance(node, dict):
        title = str(node.get("title") or node.get("name") or name)
        text = node.get("text") or node.get("content")
        if isinstance(text, str) and text.strip():
            blobs.append((title, text))
        for key, value in node.items():
            blobs.extend(_collect_text_blobs(value, str(key)))
    elif isinstance(node, list):
        for item in node:
            blobs.extend(_collect_text_blobs(item, name))
    return blobs
