"""DailyMed SPL lookup keyed by an already-validated RXCUI.

Official API: https://dailymed.nlm.nih.gov/dailymed/services/v2/
The SPL list endpoint is JSON. The complete label for a SET ID is XML only;
requesting `{SETID}.json` returns HTTP 415. Label facts are copied from SPL
records. They are not generated by a model.
"""

from __future__ import annotations

from dataclasses import dataclass
from xml.etree import ElementTree

import httpx

from app.sources.exceptions import SourceParseError
from app.sources.http import as_list, get_json, get_text, new_client

DAILYMED_BASE_URL = "https://dailymed.nlm.nih.gov/dailymed/services/v2"
SOURCE_CODE = "DAILYMED"


@dataclass(frozen=True)
class DailyMedLabel:
    set_id: str
    rxcui: str
    title: str | None
    indication_text: str | None
    contraindications_text: str | None
    warnings_text: str | None
    dosage_text: str | None
    active_ingredient: str | None


class DailyMedClient:
    def __init__(
        self,
        *,
        client: httpx.Client | None = None,
        transport: httpx.BaseTransport | None = None,
        base_url: str = DAILYMED_BASE_URL,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self._owns_client = client is None
        self._client = client or new_client(
            transport=transport,
            headers={"Accept": "application/json, application/xml, text/xml, */*"},
        )

    def close(self) -> None:
        if self._owns_client:
            self._client.close()

    def labels_for_rxcui(self, rxcui: str, *, limit: int = 3) -> list[DailyMedLabel]:
        code = rxcui.strip()
        if code == "":
            raise ValueError("RXCUI is required for DailyMed lookup")
        listing = get_json(
            self._client,
            f"{self.base_url}/spls.json",
            source_code=SOURCE_CODE,
            params={"rxcui": code, "pagesize": str(limit)},
        )
        if not isinstance(listing, dict):
            return []
        data = as_list(listing.get("data"))
        labels: list[DailyMedLabel] = []
        for row in data[:limit]:
            if not isinstance(row, dict):
                continue
            set_id = str(row.get("setid") or row.get("set_id") or "").strip()
            title = str(row.get("title") or "").strip() or None
            if set_id == "":
                continue
            xml_text = get_text(
                self._client,
                f"{self.base_url}/spls/{set_id}.xml",
                source_code=SOURCE_CODE,
            )
            sections = extract_spl_sections(xml_text)
            labels.append(
                DailyMedLabel(
                    set_id=set_id,
                    rxcui=code,
                    title=title,
                    indication_text=sections.get("indications"),
                    contraindications_text=sections.get("contraindications"),
                    warnings_text=sections.get("warnings"),
                    dosage_text=sections.get("dosage"),
                    active_ingredient=sections.get("active_ingredient"),
                )
            )
        return labels


def extract_spl_sections(xml_text: str) -> dict[str, str]:
    """Copy named SPL sections from official HL7 XML. JSON is not a SET ID format."""
    try:
        root = ElementTree.fromstring(xml_text)
    except ElementTree.ParseError as exc:
        raise SourceParseError("DailyMed SPL XML could not be parsed") from exc
    blobs = _collect_section_blobs(root)
    mapping = {
        "indications": ("indication", "indications and usage", "indications & usage"),
        "contraindications": ("contraindication",),
        "warnings": ("warning", "boxed warning", "precautions"),
        "dosage": (
            "dosage and administration",
            "dosage & administration",
            "dosage",
            "dosing",
            "monitoring",
        ),
        "active_ingredient": ("active ingredient",),
    }
    found: dict[str, str] = {}
    for target, needles in mapping.items():
        for blob_name, blob_text in blobs:
            lowered = blob_name.casefold()
            if any(needle in lowered for needle in needles) and blob_text.strip():
                previous = found.get(target)
                found[target] = (
                    blob_text.strip() if previous is None else f"{previous} {blob_text.strip()}"
                )
    return found


def _collect_section_blobs(root: ElementTree.Element) -> list[tuple[str, str]]:
    blobs: list[tuple[str, str]] = []
    for section in _iter_local(root, "section"):
        names: list[str] = []
        code_el = _first_child(section, "code")
        if code_el is not None:
            display = (code_el.attrib.get("displayName") or "").strip()
            if display:
                names.append(display)
        title_el = _first_child(section, "title")
        if title_el is not None:
            title = " ".join("".join(title_el.itertext()).split())
            if title:
                names.append(title)
        text_el = _first_child(section, "text")
        text = " ".join("".join(text_el.itertext()).split()) if text_el is not None else ""
        blob_name = " ".join(names)
        if text:
            blobs.append((blob_name, text))
    return blobs


def _iter_local(element: ElementTree.Element, local_name: str) -> list[ElementTree.Element]:
    return [item for item in element.iter() if _local_name(item.tag) == local_name]


def _first_child(element: ElementTree.Element, local_name: str) -> ElementTree.Element | None:
    for child in list(element):
        if _local_name(child.tag) == local_name:
            return child
    return None


def _local_name(tag: str) -> str:
    if tag.startswith("{") and "}" in tag:
        return tag.split("}", 1)[1]
    return tag
